### ISSUE TITLE
Gracefully handle at least 1 geoip service being down

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#126]
We have 0 connected probes 

```
[2022-05-14 09:27:47] [DEBUG] [24] [general] disconnected from API. (transport close)
[2022-05-14 09:28:13] [ERROR] [24] [general] connection to API failed failed to collect probe metadata
```

looks like because ipinfo is down we broke the whole service?

and last commit stops re-connects from "failed to collect probe metadata" so they will never re-connect until an update is released

I think we should be able to gracefully handle at least 1 geoip service being down

**Comment by zarianec** [comment]
Try to remove maxmind or ipinfo api key from the env vars ;)

**Comment by jimaek** [comment]
Ipinfo is broken right now anyway due to making 200k requests. Some probes can't resolve cities because of that it seems. I'm not sure why.
So it's not as simple

**Comment by patrykcieszkowski** [comment]
don't we cover this case in unit tests?

**Comment by patrykcieszkowski** [comment]
> don't we cover this case in unit tests?

We do:
https://github.com/jsdelivr/globalping/blob/master/test/tests/unit/geoip.test.ts#L55
https://github.com/jsdelivr/globalping/blob/master/test/tests/unit/geoip.test.ts#L82
https://github.com/jsdelivr/globalping/blob/master/test/tests/unit/geoip.test.ts#L109

**Comment by jimaek** [comment]
You mean the current issue with no city is because ipinfo is the only of 3 providers that has a city field? Can you confirm that manually?

**Comment by patrykcieszkowski** [comment]
I said we do handle geoip results just fine, even if one provider is down. City issue. But for some IPs - yes, ipinfo is the only one with this field.
