### ISSUE TITLE
Private IPs improvements

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#134]
I think I've seen 2 small issues with our private IP blocking. Can you please check what we can do about it?

1. We often shortly flash the real result in the output before returning the error message. It happens in all tests. Just set 192.168.1.1.nip.io as endpoint. It would be good to completely avoid doing that. (This happens if the endpoint actually exists in the LAN). What are our options?
2. It seems that if you set a non-existing endpoint, e.g. 192.168.1.12.nip.io and run the test it will wait until the 30s timeout before returning the error. But I dont think we need to wait, all 3 tools seem to return the resolved IP immediately before getting stuck waiting for responses

**Comment by patrykcieszkowski** [comment]
Blocking `nip.io` or targets containing private IP as part of the domain name doesn't make sense, since anybody can spawn such a service. Our best bet would be querying the DNS before `ping` request is executed.

**Comment by patrykcieszkowski** [comment]
Wym. That's what we agreed for - show all results IRL if possible, block if the final field is a private IP (dns). Gateway is always a private IP.

**Comment by patrykcieszkowski** [comment]
> 3\. Why cant we check the IP in the output of the first row before sending back to the API and stop the test? The first row appears immediately, so it wont block the real-time part in any way.
>         Traceroute does the same `traceroute to 192.168.1.100.nip.io (192.168.1.100), 30 hops max, 60 byte packets`

but we do!

https://github.com/jsdelivr/globalping-probe/blob/master/src/command/traceroute-command.ts#L116
https://github.com/jsdelivr/globalping-probe/blob/master/src/command/ping-command.ts#L96

**Comment by jimaek** [comment]
What about the second part of the issue? If we already read the first row then no reason to wait for the timeout before detecting it as private ip

**Comment by patrykcieszkowski** [comment]
We kill the process on private IP detection, so the response should be sent out immidiatelly.

**Comment by jimaek** [comment]
There is no difference if the IP is present in the network or not. The DNS record is resolvable 100% of the time. And ping makes the resolved IP available in the first row. So why do we need to wait 15/30seconds to block the test?
Just take the resolved IP and check it if its private or not without waiting for anything. If its private then kill the test.

**Comment by patrykcieszkowski** [comment]
Read again what I said.

There is a difference. I just told you - with our current implementation, execa doesn't report `data` event on stdout on header's appearance. On unresolved ping  - the response we catch is the timeout error.

**Comment by jimaek** [comment]
I still dont understand what you want to say. Its impossible to do?

**Comment by jimaek** [comment]
I think point 1 was fixed in 0.5.1. Maybe also run a test yourself to confirm.
Now need to fix point 2 as well to close this issue
