### ISSUE TITLE
Empty results

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#135]
Not sure yet how but some results are empty. In theory it should never happen, we must return an error.

Input https://dl.dropboxusercontent.com/s/0f6b0a8k34ns15m/chrome_2022-05-25_19-53-59.png

Result
https://api.globalping.io/v1/measurements/n5IzFV5i2h4Gyeg0

```
{
"id": "n5IzFV5i2h4Gyeg0",
"type": "traceroute",
"status": "finished",
"createdAt": 1653501115851,
"updatedAt": 1653501145857,
"results": []
}
```

**Comment by jimaek** [comment]
Looks like it was related to outdated PR deployment. Closing for now

**Comment by jimaek** [comment]
Nope, seems unrelated after all

```
{"id":"jWGAwDnXqDUYKpsi","type":"traceroute","status":"finished","createdAt":1653502279205,"updatedAt":1653502309211,"results":[]}
```

**Comment by patrykcieszkowski** [comment]
I don't think we changed anything to target this issue since then, but I can't replicate it. Any tips?

**Comment by jimaek** [comment]
I guess lets close it for now and see if it happens again
