### ISSUE TITLE
Filter locations

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#142]
I keep running into an issue where I want to run a test from a specific probe location. e.g. Amazon in Sydney.
Right now its impossible. IDs are probably not the safest solution for now, so #94 can stay open while we think about it.

Previous idea _Originally posted by @patrykcieszkowski in https://github.com/jsdelivr/globalping/issues/94#issuecomment-1101929656_

> We could expand the location query mechanism to `sticky` values

> We could do something like this:
> ```
> [
>     {
>         "type": "nested",
>         "value": [
>             {
>                 "type": "country",
>                 "value": "gb"
>             },
>             {
>                 "type": "network",
>                 "value": "virgin media limited"
>             }
>         ],
>         "limit": 1
>     }
> ]
> ```
> 
> the logic behind:
> - we add a new `type`, accepting `Location[]` as a value
> - the type can only be used top level
> - second-level filter (filter inside `nested` type) can't supply `limit` value
> - values within the `nested` type are filtered for common match.

Sounds interesting but maybe a bit too complicated? 

How about something like this

```
{
  "measurement": {
    "type": "ping",
    "target": "google.com"
  },
  "locations": [
   "filter": "all", //default and optional. Maintains our existing logic. This will return 3 results.
    {
      "type": "country",
      "value": "pl",
      "limit": 1
    },
    {
      "type": "country",
      "value": "de",
      "limit": 1
    },
    {
      "type": "magic",
      "value": "cyprus",
      "limit": 1
    }
  ]
}
```

To combine:

```
{
  "measurement": {
    "type": "ping",
    "target": "google.com",
    "limit": 2 //only global limit would work with the filter I think.
  },
  "locations": [
   "filter": "combine", // this means it will look for 2 probes with country:PL AND asn:8475.
    {
      "type": "country",
      "value": "pl",
    },
    {
      "type": "asn",
      "value": "8475",
    }
  ]
}
```
It stays almost the same and the user can optionally add the filter parameter without changing the API too much

Additionally for magic field we could add special char support. 

Like `magic:sydney+amazon` = Probes that have both sydney and amazon parameters. In this case it would just be 1 probe.

**Comment by patrykcieszkowski** [comment]
You can't do that. `Locations[]` is an array, and in your example the `filter` variable would be set on its own - it would have to be wrapped around an object.

```
{ "filter": "all" }
```

Frankly speaking, it seems like changes in logic would be pretty similar, but the end result wouldn't be as readable and user friendly. 

As for the `magic` query, we could probably do that right now, it would be one liner.

**Comment by jimaek** [comment]
I wonder if supporting this logic only in the magic field and nowhere else would be a good idea. What do you think?

**Comment by patrykcieszkowski** [comment]
> I wonder if supporting this logic only in the magic field and nowhere else would be a good idea. What do you think?

I think it's a good start, but I would like to see it implemented in standard queries at some point.

**Comment by jimaek** [comment]
What if we moved `filter` into the `measurement` array? So the user is basically requesting how he wants the measurement results to get processed

**Comment by patrykcieszkowski** [comment]
Yeah, that would work then, thats pretty much how we define global limit. But again, the underlying logic would be the same as in nested location objects. We should think of which solution would be better long term.

**Comment by jimaek** [comment]
Lets proceed with filter in measurement then. It should solve the problem with minimal changes in the format.

```
{
  "measurement": {
    "type": "ping",
    "target": "google.com",
    "limit": 2, //only global limit would work with the filter I think.
     "filter": "combine", // this means it will look for 2 probes with country:PL AND asn:8475.
  },
  "locations": [
     {
      "type": "country",
      "value": "pl",
    },
    {
      "type": "asn",
      "value": "8475",
    }
  ]
}
```

@MartinKolarik will later review the API overall as well
