### ISSUE TITLE
The http command should include response body and headers for errors

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#149]
If there's an error while handling the HTTP command, we currently return empty `rawBody` and `rawHeaders`. For `HTTPError` type, those properties should be returned just like they are for non-error responses. I'd say `rawOutput` should also be the body of the response, and not the error message as it is now.

Probably what we want is to simply turn this off: https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#throwhttperrors

**Comment by patrykcieszkowski** [comment]
I'm confused as to what you're referring to - we capture and output everything that's supplied.

**Comment by patrykcieszkowski** [comment]
Strangly enough, `throwHttpErrors` toggle doesn't seem to change the bahaviour of stream at all. It throws an error regardless of it's value.

**Comment by MartinKolarik** [comment]
I'm not sure right now how the option works for streams but the alternative solution is to simply check for the error class.
