### ISSUE TITLE
Reduce IO in malware validation

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#151]
The malware validation in https://github.com/jsdelivr/globalping/tree/44999e1b1a921ee35ff4b4f7b6e753a130c5c358/src/lib/malware has several issues:
 - [ ] [sync fs functions are used during request/response lifecycle](https://github.com/jsdelivr/globalping/blob/44999e1b1a921ee35ff4b4f7b6e753a130c5c358/src/lib/malware/domain.ts#L44) (joi has `validateAsync` function if needed),
 - [ ] the lists are unnecessarily read from fs and parsed on every call, instead of being read on startup and then accessed from memory,
 - [ ] the async versions seem to be *only* used in tests, while the sync versions don't have unit tests.

**Comment by patrykcieszkowski** [comment]
IO querying is a valid point. I believe the initial idea was to scan databases in interval, and their size would be hard to predict so we opted for IO calls per connection. Finally, we scan them per-build basis (once a day), and their size isn't all that terrible. We might as well store them in-memory.

For joi methods, if we keep the list in-memory, they


> * the async versions seem to be _only_ used in tests, while the sync versions don't have unit tests.

these tho methods identical, with exception of one using synchronious IO call. There's no need to test them both.

**Comment by MartinKolarik** [comment]
> these two methods identical, with exception of one using synchronious IO call. There's no need to test them both.

yes but the one that's tested doesn't seem to be used anywhere outside the tests so not sure why it's even there
