### ISSUE TITLE
Change location schema

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#156]
The current schema allows specifying only one key/value pair per object, e.g.

```
locations: [
  { "type": "continent", "value": "eu" }
]
```

That means to support changing behavior from "OR" to "AND" when multiple location types are specified, we need an extra switch `filter: combined` 

```
filter: "combined",
locations: [
  { "type": "continent", "value": "eu" }
  { "type": "network", "value": "virgin media limited" }
]
```

This seems unnecessarily complex and is still somewhat limited because you can't mix AND/OR behavior within one request.

It seems to me a better format here would be `{ [key]: value }`, e.g.:

```
locations: [
  { continent: "eu", network: "virgin media limited" }
]
```

This format makes it immediately obvious that combining multiple values is likely supported for AND behavior, and no separate switch is needed. As a bonus, it is possible to combine AND/OR together:

```
// runs in "virgin media limited", once in EU and once in NA
locations: [
  { continent: "eu", network: "virgin media limited" },
  { continent: "na", network: "virgin media limited" }
]
```

Unless there are strong reasons for the current format, I suggest changing this.

**Comment by patrykcieszkowski** [comment]
We've been through this a couple of times over the recent few months. My original idea was to implement nested locations, but it wasn't approved by neither @jimaek nor @zarianec.

**Comment by patrykcieszkowski** [comment]
Here's the most recent reference to it: https://github.com/jsdelivr/globalping/issues/142

I don't see any disadvantages, in fact IMO it's far more readable and powerful.

**Comment by jimaek** [comment]
The main reason I pushed for the filter was to release the feature faster. 
I am not against refactoring it now that it's working, but I think we need Artem here, because I am curious what was his original reason to make the API in this way. @zarianec

**Comment by MartinKolarik** [comment]
Indeed, I was even tagged there. My only small issue is that we'd mix the location specifiers with the `limit` in the new format, e.g. `{ country: 'CZ', network: '...', limit: 1 }`  but overall I think the format is still much more intuitive to users.

**Comment by zarianec** [comment]
The original reason was to keep API more formal. Somehow we missed a use-case with AND filters back then so didn't consider it while designing the API.

But Martin's variant definitely fits better for use-cases we have now.

**Comment by MartinKolarik** [comment]
Ok, let's proceed with this change then.

**Comment by patrykcieszkowski** [comment]
Adding a `nested` type, like I proposed would make it far easier to implement, due to nature of our current filtering system; schemas, types, router, tests. And it looks far more readable to me. Why don't we go with that?

**Comment by patrykcieszkowski** [comment]
Just like in the mentioned ticket:

```json
[
    {
        "type": "nested",
        "value": [
            {
                "type": "country",
                "value": "gb"
            },
            {
                "type": "network",
                "value": "virgin media limited"
            }
        ],
        "limit": 1
    }
]
```

vs:
```json
[
    {
        "country": "gb",
        "network": "virgin media limited",
        "limit": 1
    }
]
```

The first one, is essentially what we're doing under the hood with our current `combined` toggle solution.

**Comment by patrykcieszkowski** [comment]
> Definitely harder to document and explain

that's a pretty subjective statement. The current schema is already documented, and IMO - the docs are pretty self explanatory. The change would just consist of adding a new type, and highlighting its value type is `Location[]`. Not that complicated.

I agree - if we were to design the API from scratch, your schema would probably be the way to go (I would probably group these k/v's into a mutual object, to seperate them from the `limit` key). I don't see however, a benefit of rewriting the entire location schema, while there's an equally good, and less intrusive solution at hand and we've manually tested the current schema for months.

**Comment by jimaek** [comment]
I would actually prefer the current version we have live to nested. It looks too complicated and it's not obvious how it works.

**Comment by patrykcieszkowski** [comment]
Just a reminder, `magic` type supports nesting aleady, so that can be used for AND/OR scenarios with `filter: combined` disabled.

**Comment by MartinKolarik** [comment]
> I agree - if we were to design the API from scratch, your schema would probably be the way to go

Good. We're at a point when we still can do that, hence my suggestions. As soon as we mark it as stable we won't be able to and indeed, then the "intrusiveness" would be the main factor. Right now, I'm aiming to make the format more intuitive because we still can.

> that's a pretty subjective statement. The current schema is already documented, and IMO - the docs are pretty self explanatory. The change would just consist of adding a new type, and highlighting its value type is Location[]. Not that complicated.

It's a statement based also on the later goal of providing a standardized OAS document. Your solution needs a special switch that changes `Location` to `Location[]` which is a mess compared to having one object with keys - and it's a mess also to understand it as a user from the current docs.
