### ISSUE TITLE
Update schema for creating measurements

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#159]
- [ ] 1. For DNS type, change the params from:

```js
"measurement": {
    "query": {
        "protocol": "UDP",
        "type": "A",
        "port": 53,
        "resolver": "1.1.1.1"
    }
}
```

to

```js
"measurement": {
    "query": {
        "type": "A",
    },
    "protocol": "UDP",
    "port": 53,
    "resolver": "1.1.1.1"
}
```

Neither of the three values is actually a property of the query, and for other measurement types, we even have protocol/port params already, without extra nesting.

- [ ] 2. Move properties `type` and `target` outside of the `measurement` object and rename `measurement` to `measurementOptions`:

```
{
    "measurement": {
        "type": "dns",
        "target": "google.com",
        "query": {
            "protocol": "UDP",
            "type": "A",
            "port": 53,
            "resolver": "1.1.1.1"
        }
    },
    "locations": [],
    "limit": 1
}
```

=> 

```
{
    "type": "dns",
    "target": "google.com",
    "measurementOptions": {
        "query": {
            "type": "A",
        },
        "protocol": "UDP",
        "port": 53,
        "resolver": "1.1.1.1"
    },
    "locations": [],
    "limit": 1
}
```

This separates the shared and required properties from those that are optional and measurements-specific, making it easier to make sense of what changes between measurement types. Also, the naming makes more sense because "measurement" is represented by the whole payload which includes location/limit as well.

**Comment by patrykcieszkowski** [comment]
number `2` won't fly, and following that logic, the `query` field is taking that role (`1`).

The `measurement` object is a container for every measurement-specific parameter there is to be supplied; it's structure doesn't change, up until the point it reaches the probe. Yes, including measurement type value, and the target. All of these are necessary for the probe to start the test. The seperation you're describing is achieved with the `query` object, even though not all measurement types follow that structure - and that should be fixed. I see no added value of that change.

**Comment by MartinKolarik** [comment]
> The measurement object is a container for every measurement-specific parameter there is to be supplied; it's structure doesn't change, up until the point it reaches the probe. Yes, including measurement type value, and the target. All of these are necessary for the probe to start the test. 

That's your implementation detail I don't care about at all as a user. What you send to the probe doesn't need to match 1:1 the payload from the user (just take the fields from the outer object and send them as you wish).

**Comment by patrykcieszkowski** [comment]
Not an argument. There's no value coming from the proposed change of schema.

**Comment by MartinKolarik** [comment]
The value is cleaner naming and better distinction between shared/required and measurement-specific/optional parameters. It's something you may disagree with but as I said in my previous comment, there's no implementation problem with doing it, so please just do it.

**Comment by patrykcieszkowski** [comment]
The whole shtick with refactoring location filters schema, rather than adding a new type, was the idea a user would have to update multiple objects, if they were to modify filter parameters, and we want to simplify that - this change would be the exact opposite of that mindset. It's more accesable for user to have a hot-swappable object, than haivng values spread all over the request body.

**Comment by MartinKolarik** [comment]
> The whole shtick with refactoring location filters schema, rather than adding a new type, was the idea a user would have to update multiple objects, if they were to modify filter parameters, and we want to simplify that - this change would be the exact opposite of that mindset. It's more accesable for user to have a hot-swappable object, than haivng values spread all over the request body.

This is different. Locations were about changing a shape of the data depending on the behavior. Here we don't change the shape, just the values.

Also, "all over the request body" is part of the my problem with the current naming. You're looking at it as if "location" and "limit" were somehow not the part of the "measurement" but conceptually I consider the whole body to be "the" measurement. E.g., if I were writing a request, it would be:

```js
let measurement = {
  type: 'A',
  measurementOptions: { ... },
  locations: [ ... ],
  limit: 1
};

fetch(endpoint, { body: JSON.stringify(measurement ) })
```

instead of

```js
let payload = {
  measurement: {
    type: 'A',
    ...
  },
  locations: [ ... ],
  limit: 1
};

fetch(endpoint, { body: JSON.stringify(payload) })
```

Implementation-wise, yes, part of that information is used only by the API, and part is sent to the probe, but for the API user, all of it, together, is a measurement.

**Comment by patrykcieszkowski** [comment]
The definition of `target` is also type-dependent, so that's another thing to consider.

Either way, I can't move on with this, until we merge #166.
