### ISSUE TITLE
Ensure we send meaningful errors for schema validation

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#160]
E.g. sending an invalid measurement type right now returns `\"measurement.type\" must be [http]` instead of `\"measurement.type\" must be on of [ping, http, ...]` - this particular thing might be fixed after #159 on its own but we should have a test for validation of each possible property - both to ensure that there actually is validation, and that the error makes sense.

**Comment by patrykcieszkowski** [comment]
I'm not really sure how to tackle this issue, nor what a sensible error messages would have to look like.

Here's an error message produced by Joi on a typo:

```json
{
  "_original": {
    "type": "ping",
    "target": "google.com",
    "locations": [],
    "measurementOptions": {
      "pakcets": 2
    }
  },
  "details": [
    {
      "message": "\"measurementOptions.pakcets\" is not allowed",
      "path": [
        "measurementOptions",
        "pakcets"
      ],
      "type": "object.unknown",
      "context": {
        "child": "pakcets",
        "label": "measurementOptions.pakcets",
        "value": 2,
        "key": "pakcets"
      }
    }
  ]
}
```

The error message is pretty vague, it doesn't output us a list of available properties.

**Comment by MartinKolarik** [comment]
I'm ok with the message in your example, it's the best you can do with typos without attempting fuzzy matching. My problem was mostly with the `alternatives()` handling. In my example above, it says "type must be [http]" which is plain wrong since type has five possible values.

**Comment by patrykcieszkowski** [comment]
I consider this issue resolved by now. Can't find any error message that wouldn't make much sense.
