### ISSUE TITLE
Fix geoip logic

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#161]
The logic should be as follows.

City:
1. Find the best city match based on the number of the same values (this is implemented correctly).
1.1. If ipinfo + maxmind have the same result, use ipinfo (this matters because we then use other values like coordinates/asn from the "best match" and they can differ even between providers with the same city).
1.2. If ipinfo + fastly have the same result, use ipinfo. 
1.3. If maxmind + fastly have the same result, use maxmind,
1.4. If all three providers return a different city, the priority is: ipinfo, maxmind (right now it's random).
1.5. If Fastly is the only to return a city, consider the location unresolved and drop the probe.

ASN/Network:
1. If ipinfo and maxmind agreed on the city, use ipinfo.
1.1. If ipinfo doesn't have network data, use maxmind.
2. Use the provider with "best match" for the city.
2.1 If the best match for the city doesn't have network data, drop the probe (with the exception of the specific case 1.1).

---

3. Handle a case when ipinfo doesn't return org, which currently throws: https://github.com/jsdelivr/globalping/blob/7b96ead590866a21613a35a3d2388dd7bf0c55ab/src/lib/geoip/providers/ipinfo.ts#L24
4. Test all the cases.
5. Increase default cache time to 3 days.

**Comment by patrykcieszkowski** [comment]
We've refactored geoip mechanism at least 3 times since the start of the project, and this is nothing like we discussed in the past. Where all that comes from?

**Comment by MartinKolarik** [comment]
We had a long discussion with @jimaek two days ago. All tasks I'm posting right now are the results of that discussion. In this specific case, the logic simply doesn't match what he previously described.

**Comment by MartinKolarik** [comment]
If you read it in detail, it's mostly changes about changing random behavior when providers don't agree, to a well defined order.

**Comment by MartinKolarik** [comment]
Some extra details, as we also did a test with 8k IPs this week:
 - Fastly was confirmed to be the least accurate.
 - There was *never* a case where Fastly would be the only one to return a city.

**Comment by patrykcieszkowski** [comment]
Can you explain to me in more details the ASN/Network mechanism? Especially this part

> 2\. Use the provider with "best match" for the city.
>         2.1 If the best match for the city doesn't have network data, drop the probe (with the exception of the specific case 1.1).

**Comment by MartinKolarik** [comment]
> 

A provider may return city details but have empty ASN/network fields. We want to use the same provider for ASN that we used for the city, except if multiple providers returned the same city, then a case like 1.1 is possible. Fastly should *never* be used for ASN, hence there's special rules only for ipinfo/maxmind, and dropping otherwise.

**Comment by patrykcieszkowski** [comment]
@MartinKolarik can you review the changes I've made to the city-match mechanism in #164, and let me know if its outcome will match the expected behaviour for network details? I'm pretty sure that's exactly what we're doing, but I might be wrong.

**Comment by MartinKolarik** [comment]
Sure, also one update. Fastly can return strings "reserved" and "private" for the city name, replace those with empty strings. It won't impact the behavior right now since we're going to use Fastly results only if they match with some other provider, but just in case, for the future.

**Comment by MartinKolarik** [comment]
@patrykcieszkowski for network, I still see maxmind having the highest priority, which doesn't match the description above.

**Comment by patrykcieszkowski** [comment]
> @patrykcieszkowski for network, I still see maxmind having the highest priority, which doesn't match the description above.

I'm aware. Besides the maxmind/best match priority, are you seeing anything that wouldn't match the desired network match algorithm? I'm trying to understand what needs to be done.

**Comment by MartinKolarik** [comment]
Well, I'm not sure what to tell you, really. I guess it's close, but you see yourself that it doesn't fully match, so update it to the cases I described and then I can check.
