### ISSUE TITLE
Add DNS resolver to responses

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#165]
How about we add a global resolver field to all responses? So that when a user doesn't provide their own and uses the default he could know which one is that. 

We could read local resolvers and if it's a private IP say `resolvers: private` or `local` otherwise 

```
"resolvers": {
"1.1.1.1",
"8.8.8.8"
}
```

It would be useful especially in case of home hosted probes that would have ISP DNS resolvers from DHCP.

But we need to make sure we read them correctly. 

Also since there is no way of knowing which resolver was actually used for the request we probably just have to show the whole array. Unless I am wrong and we can know the used resolver, in which case we should provide a single IP of the one that was used.

**Comment by patrykcieszkowski** [comment]
I don't see a way to tell which DNS server was used - maybe for certain commands, such as `HTTP`, but that's about it. So we'll have to report the entire array; what if the DNS pool has a mix of private and public IPs?

We should also make sure the `resolver` field will always be an array, even if user provides their own server, to avoid confusion.

**Comment by jimaek** [comment]
So if nothing was provided by the user we return full array but with private IPs censored. If user specified a resolver manually we return an array of 1.

@MartinKolarik wdyt?

**Comment by MartinKolarik** [comment]
How about instead defaulting to some predefined value, so that the behavior is consistent regardless of the network setup of the probe (set default resolvers in the docker image, or in node)?

I could see some value in being able to use the provider-default, but since the probe owners can have a custom setup on their OS/router anyway and the people making measurements have no way to request "use the default provider DNS, not a custom one" this isn't the case anyway. So maybe it would make more sense for us to simply normalize the behavior in this case.

**Comment by jimaek** [comment]
People do have the ability to request to use to use the ISP provider, don't specify a custom one, we just don't guarantee it will be ISP and not Google.

In the future we could even detect those probes and tag them to allow users to run tests only on probes using ISP resolvers

**Comment by MartinKolarik** [comment]
Yes, they have the ability, but they don't know in advance what's going to happen in the end, hence it doesn't really fulfill the "I want to get the ISP provider" use case, at which point I'm not sure if there's any reason to not have defaults.

> In the future we could even detect those probes and tag them to allow users to run tests only on probes using ISP resolvers

I thought of it but not sure how we would actually decide what's ISP and what not.

**Comment by jimaek** [comment]
I think Martin means just setting them in the Docker container and not return anything in the API. 

In my case we return everything in JSON with filtering to hide private IPs. But even then its useful info to know if the resolving happened on a public resolver or an ISP/LAN resolver.

**Comment by jimaek** [comment]
Ok, so:
1. Add to probe.dnsResolvers in responses
2. Add to list of probes /v1/probes
3. Array, that lists configured resolvers https://nodejs.org/api/dns.html#dns_dns_getservers OR an array of 1 if the user passed a custom one. Its important to list those that were actually used.  
4. Filter the list and replace private IPs with "private" or other

Agreed?

**Comment by MartinKolarik** [comment]
We can't do 3 if it goes under the probe. But I don't think we have to. The user knows if he set custom or not, we don't have to send the custom value back.

**Comment by patrykcieszkowski** [comment]
But it is part of the measurement. Those are the DNS resolvers, the request was completed with. We can't know exactly which one was used, which is why we wanna pass the entire list.

The DNS Resolver list can change during probe's runtime, and probe details are gathered during the connection. It wouldn't be guaranteed to be accurate.

**Comment by jimaek** [comment]
Under the probe of course no, just list the included ones. But for the measurement I want to make it as clear and useful as possible and replace them with the custom one. That way its clear which one the query used, custom or defaults

**Comment by MartinKolarik** [comment]
So just a property with two const values? I suppose we could though I don't see much value in it.

**Comment by patrykcieszkowski** [comment]
> When I say "which one is used" I dont mean the specific one of a list of 10 resolvers a probe might have. I mean default or custom. Nothing specific

I know what you mean - you want either a list of available DNS, which were available during the request or a DNS specified by the user. We're on the same page.

I'm arguing the dns list shouldn't go under the `probe` settings.

**Comment by MartinKolarik** [comment]
> The DNS Resolver list can change during probe's runtime, and probe details are gathered during the connection. It wouldn't be guaranteed to be accurate.

Yes, it is something to consider. We could query it during each measurement and then it would no longer be a property of probe. But I don't think this is necessary.

**Comment by jimaek** [comment]
Technically you're right they can change, but the chances are super low. Its not like people change their DNS resolvers 10 times per day. And our probes auto-die once per week anyway, it should be enough to pick up the latest accurate resolvers

**Comment by MartinKolarik** [comment]
Ok so `probe.dnsResolvers` and `result.dnsResolverType` with values "default" and "custom".

**Comment by MartinKolarik** [comment]
@patrykcieszkowski final version in the comment above.
