### ISSUE TITLE
Version check

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#177]
Why is it so strict? All it needs to check that the breaking change was at 0.9 and force upgrade anything below and ignore anything above

**Comment by MartinKolarik** [comment]
@patrykcieszkowski I think we can do `>= 0.9.0`

**Comment by patrykcieszkowski** [comment]
> Why is it so strict? All it needs to check that the breaking change was at 0.9 and force upgrade anything below and ignore anything above

I must be missing something. It does allow versions above to pass through.

**Comment by MartinKolarik** [comment]
Yes but only some. `^1.0.0` means `>= 1.0.0 and < 2.0.0` and with `0.x.x` versions, as is our case, `^0.9.0` means only `>= 0.9.0 and < 0.10.0`

What we want is quite simply "anything above"
