### ISSUE TITLE
Incorrect probesCount reported

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#185]
```
POST
{"type":"http","target":"www.google.com","measurementOptions":{"request":{"method":"GET"}},"locations":[],"limit":200}
```

=>

```
{
  "id": "KtnF769e689WyglO",
  "probesCount": 201
}
```

The actual `results` array only has 200 items.

**Comment by MartinKolarik** [comment]
Actually in some cases, but not all, the results also have 201 items:

![image](https://user-images.githubusercontent.com/6192491/181594390-b0665b0b-e2e9-4629-9c3e-602697b2548d.png)

**Comment by patrykcieszkowski** [comment]
The `probesCount` value is the length of the array holding selected probes.

But the bug in itself is interesting. I can't replicate it on limits lower than `200`. In fact, setting the limit to `300` also works fine. It only seems to be happening on rage 200-240. 

And I can't replicate it by testing the probe router.

**Comment by MartinKolarik** [comment]
In the first case, I got `201` in the POST response. There, you don't have the array, so can't compare. But the final measurement had `200` results. In the second case, both were 201.

**Comment by patrykcieszkowski** [comment]
> In the first case, I got `201` in the POST response. There, you don't have the array, so can't compare. But the final measurement had `200` results. In the second case, both were 201.

Result's aren't guaranteed. There are some probes which constantly reconnect due to their distance, and I suspect that might be causing the issue where the final result count didn't meet the count of initially assigned probes.

**Comment by MartinKolarik** [comment]
It could. Why 201 is still a question.

**Comment by patrykcieszkowski** [comment]
@MartinKolarik can you recreate this issue now? I can't, neither on the prod server or on my localhost

**Comment by MartinKolarik** [comment]
Reopening as I came across this again. I suspect [this line](https://github.com/jsdelivr/globalping/blob/a09d0448013911849be94f292c88db0ea4d8e7c8/src/probe/sockets-location-filter.ts#L89) to be the cause - we add multiple probes without checking for the limit and depending on the weights and rounding, the computed `count` may likely be one more than needed. The easiest fix to avoid constant checks is maybe just to call `.slice()` at the end?
