### ISSUE TITLE
Handling of unresolved addresses and timeouts

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#188]
Traceroute:

```
"resolvedAddress": "74.125.200.100",
"resolvedHostname": "*",
```

Here the hostname failed to resolve, which is represented by `*` in the raw output. For the parsed output, it seems more reasonable to represent this with `null`. Otherwise, we need to document `*` as a special value, which we do for `private` IPs, but I don't see the point here - `private` really is a special case that needs a name because it's not just "empty" but here `null` works.

Also, note that MTR returns empty strings, at least in a case when the initial name isn't resolved - that should likely be changed to `null` too

![image](https://user-images.githubusercontent.com/6192491/181773251-547c2a08-76d5-4007-9f90-8705bcf3a9d1.png)
 On the other hand, traceroute/ping doesn't return the extra properties at all for this case, not sure if we can fix that:

![image](https://user-images.githubusercontent.com/6192491/181773429-38611461-f238-4528-af90-e85718443329.png)

And HTTP returns default/empty values similar to MTR.

---

```
{
    "resolvedHostname": "*",
    "resolvedAddress": "*",
    "timings": []
},
```

Here the hop timed out. For MTR, I believe we settled for `null` in this case: https://github.com/jsdelivr/globalping/issues/157#issuecomment-1184198493

**Comment by patrykcieszkowski** [comment]
Nulls are terribly inconvinient to work with, and I'm not sure if that would be a good move from the UX perspective either.

**Comment by MartinKolarik** [comment]
Are they now? I thought except the eslint configuration, we didn't have problems with them. And they have a clear meaning at least.

**Comment by patrykcieszkowski** [comment]
It's not just eslint config, but the TypeScript on it's own. While defining a multi-type variable, you gotta double check its type whenever you do anything on it, even if you're convinced it's of certain type.

The issue with Eslint was the fact it doesn't lile `null`s. That can be turned off.

If we really wanna go that route, we might have to just implement a final-parse method and keep their types seperate.

**Comment by MartinKolarik** [comment]
> It's not just eslint config, but the TypeScript on it's own. While defining a multi-type variable, you gotta double check its type whenever you do anything on it, even if you're convinced it's of certain type.

But that's good, isn't it? If you are "convinced" it's either because there's a check earlier in the code, which TS should understand as well, e.g. `if (value !== null) { ... }` or you really should check.

**Comment by MartinKolarik** [comment]
If you tell me it's always a string, I'll write something like ``new URL(http://`${resolvedHostname}`)`` and later be surprised that it throws in some cases because `resolvedHostname` isn't actually valid.

**Comment by patrykcieszkowski** [comment]
How's that a good thing? That leads to an unnecessary mess in code.



> If you tell me it's always a string, I'll write something like `` new URL(http://`${resolvedHostname}`) `` and later be surprised that it throws in some cases because `resolvedHostname` isn't actually valid.
The output of the `URL()` constructor is an object, TS won't accept it as a value. That's completely different.

**Comment by MartinKolarik** [comment]
It's not about the `URL` returns but what it takes as an argument. The example wasn't very good because TS doesn't actually mind the null when it's part of the template string, but for `new URL(resolvedHostname)` it would complain with "Argument of type 'string | null' is not assignable to parameter of type 'string | URL'." and that's good. So yes the "mess" if by that you mean properly checking the value is what you expect, is good.

**Comment by MartinKolarik** [comment]
But maybe more to the point. We agreed to use nulls in the MTR case and I belive that's even implemented now, isn't it?

**Comment by patrykcieszkowski** [comment]
And the act of having to constantly check for the value is a mess and it's not a good thing. At all. You should avoid it if possible - having a single-type deals with it.

Like I said, the best way to deal with it would be to re-cast the result object when we output the value. That way we could avoic these conflicts.

> But maybe more to the point. We agreed to use nulls in the MTR case and I belive that's even implemented now, isn't it?

We never agreed for it. I clearly said I don't like multi-type castings in that thread; in that case it somewhat made sense, since setting a `0`, or negative number could lead to even more confusion  - here, I see no such benefit at all.

**Comment by MartinKolarik** [comment]
> Like I said, the best way to deal with it would be to re-cast the result object when we output the value. That way we could avoid these conflicts, and have the string|null types.

If your only concern is our own code, sure, I don't care much what type it is internally - we don't really do anything with the values. I care about the type being clear in the output.

**Comment by MartinKolarik** [comment]
The issue is only about the JSON output and how other apps interact with it. What types do we use internally to generate that output - that's up to you.

**Comment by MartinKolarik** [comment]
Also what do you think about the fields being there / not being there at all for errors?
