### ISSUE TITLE
Remove non-ascii symbols from API

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#190]
Reminder to follow up on the Slack discussion. I think everyone agrees it only creates problems and adds no value to have them.
Uppercase remains, and we can do normalization stuff to support better English names.

**Comment by patrykcieszkowski** [comment]
I'm pretty sure @ayuhito is working on a solution to replace `city` values with their englush alternatives, so that would deal with it.

**Comment by ayuhito** [comment]
We'll have to asciify it API side as some places don't have true English names e.g. České Budějovice

But it'll take care of situations where there are variants of the name which can't be simply converted to ascii e.g. Genève/Canton de Geneve -> Geneva.

I can work on this once the normaliser is done.
