### ISSUE TITLE
Refactor measurement store module

### ISSUE THREAD

**Issue by patrykcieszkowski** [jsdelivr/globalping#192]
Spawning new redis connection per measurement update is extremaly inefficient, with little to no benefit.

https://github.com/jsdelivr/globalping/blob/master/src/measurement/store.ts#L31

**Comment by jimaek** [comment]
Seems relevant https://ably.com/blog/migrating-from-node-redis-to-ioredis

**Comment by patrykcieszkowski** [comment]
Interesting. I'm working on benchmarks rn, so I guess it won't hurt testing it too.
