### ISSUE TITLE
dns: underscore char in target

### ISSUE THREAD

**Issue by patrykcieszkowski** [jsdelivr/globalping#205]
I've come across this issue yesterday, as I was renewing my certs.

Even though underscores aren't technically allowed in domain names, subdomains containing it are accepted by DNS servers, and are used for TXT fields. We don't. An example:

```
_acme-challenge.elocast.com
```

Will fail the validation step:
```
{
  "error": {
    "message": "Validation Failed",
    "type": "invalid_request_error",
    "params": {
      "target": "\"target\" must contain a valid domain name"
    }
  }
}
```

But DIG has no problem querying this path:
```
patryk@xps:~$ dig _acme-challenge.elocast.com -t TXT

; <<>> DiG 9.18.1-1ubuntu1.1-Ubuntu <<>> _acme-challenge.elocast.com -t TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21005
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;_acme-challenge.elocast.com.	IN	TXT

;; ANSWER SECTION:
_acme-challenge.elocast.com. 300 IN	TXT	"P4x8PFdPRma-X1XJ3OCqDuRG6FSdPOw39njrFFC54HY"

;; Query time: 19 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Fri Aug 26 13:51:46 BST 2022
;; MSG SIZE  rcvd: 112
```

**Comment by MartinKolarik** [comment]
This is actually a bug / poor naming in joi and it might affect other characters too. See the first two answers from https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it for details and the relevant RFCs.

**Comment by patrykcieszkowski** [comment]
interesting. So I guess we'll have to to come up with our own domain validator

**Comment by MartinKolarik** [comment]
Or open an issue at Joi first and explain the details. I only found one from the past and nobody there really had any solid arguments.

**Comment by MartinKolarik** [comment]
If they didn't want to change the default behavior, adding a flag for this (there already are several for the domain check) would be acceptable.

**Comment by MartinKolarik** [comment]
PR: https://github.com/hapijs/address/pull/43

**Comment by patrykcieszkowski** [comment]
It doesn't look like they'll acknowledge this PR anytime soon, and chances of them pushing it are pretty slim too. I pushed a replacement for Joi's domain validator. We can always revert it in the future.

https://github.com/jsdelivr/globalping/pull/207

**Comment by patrykcieszkowski** [comment]
Hapi have implemented our PR, and its added to joi as well.

https://github.com/hapijs/joi/commit/2998d8663b4f94a4af6c474dcdef2b4ffe2f896c
