### ISSUE TITLE
RUM data

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#209]
On top of the passive synthetic data we will collect using the probes it seems there is a huge need for RUM data as well. The idea is that you use RUM as a summary/overview and then switch to probes data for comparison and then to active tests to actually understand why something is happening.

And instead of collecting our own RUM data it seems there are many companies out there collecting their own and willing to share them. We need to explore the technical and functional parts of this system. 

Globalping could ingest third-party RUM data, normalize it and then make it available through a central standardized API for everyone to use.

**Comment by patrykcieszkowski** [comment]
RUM data is data on how user interacts with the website. I'm not sure what useful data could we gather from Globalping. Unless I'm missing something.

**Comment by jimaek** [comment]
RUM data can monitor the performance of all CDNs globally. I've built similar stuff in the past. The only problem is analyzing billions of data points on cheap servers

**Comment by patrykcieszkowski** [comment]
This example is pretty straight forward, store total timings and full URI of all HTTP requests, in another table store total values for specific geo + URI. Run a cronjob every 10mins and calculate the sum, avg, [...] for recent URIs. No need to analyze it in real time.

**Comment by jimaek** [comment]
Closing as I think we should focus on repeatable data that GP offers right now
