### ISSUE TITLE
Bad parsing in case of 100% loss ping requests

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#213]
If `ping` request showed 100% packet loss fields like `resolvedAdress` and some others shouldn't be null.

Steps to reproduce (may not reproduce every time):
- send measurement request with the body
```json
{
    "target": "yarmosh.by",
    "type": "ping",
    "measurementOptions": {
        "packets": 16
    },
    "limit": 500,
    "locations": []
}
```
- wait until measurement `status` is `finished`
- check all the `result` fields
Expected value:
at least `resolvedAdress` field is fulfilled
Actual value:
<img width="1038" alt="image (1)" src="https://user-images.githubusercontent.com/16905445/194161001-0dcb94fd-f243-4ae4-9ee6-8fafcd36c059.png">

**Comment by patrykcieszkowski** [comment]
Timeout is treated as an error, and generally speaking we didn't expect them to come with any meaningful data. You can't rely on exit codes, nor `stderr`, since `unbuffer` squashes everything into `stdout`. Your best bet will be detecting a non-standard response pattern, and excluding it from data parsing, but letting anything else through.

https://github.com/jsdelivr/globalping-probe/blob/master/src/command/ping-command.ts#L118-L123

**Comment by MartinKolarik** [comment]
> Timeout is treated as an error, and generally speaking we didn't expect them to come with any meaningful data. You can't rely on exit codes, nor stderr, since unbuffer squashes everything into stdout. Your best bet will be detecting a non-standard response pattern, and excluding it from data parsing, but letting anything else through.

This makes sense for node-level timeout but what's in the screenshot seems like a valid measurement result so the resolved fields should be there.

**Comment by alexey-yarmosh** [comment]
I think best option will be to try to parse the rawOutput in case of error.

In that particular case, as a user I want to have a "successful" measurement with "100% loss" as a result. And that is how it is working now. We can just add “resolvedAddress” and “stats.loss” fields to the result:
```json
=============== BEFORE
​
{
  "id": "Co3vZT9o2OldFEgQ",
  "type": "ping",
  "status": "finished",
  "createdAt": "2023-01-04T14:54:36.133Z",
  "updatedAt": "2023-01-04T14:54:46.840Z",
  "probesCount": 1,
  "results": [
    {
      "probe": {
        "continent": "EU",
        "region": "Western Europe",
        "country": "BE",
        "state": null,
        "city": "Brussels",
        "asn": 396982,
        "longitude": 4.3488,
        "latitude": 50.8505,
        "network": "Google LLC",
        "tags": [
          "gcp-europe-west1"
        ],
        "resolvers": [
          "private"
        ]
      },
      "result": {
        "rawOutput": "PING gov.pl (194.181.92.98): 56 data bytes\nRequest timeout for icmp_seq 0\nRequest timeout for icmp_seq 1\n\n--- gov.pl ping statistics ---\n3 packets transmitted, 0 packets received, 100.0% packet loss",
        "resolvedAddress": null,
        "resolvedHostname": null,
        "timings": [],
        "stats": {
          "min": null,
          "max": null,
          "avg": null,
          "loss": null
        }
      }
    }
  ]
}
​
=============== AFTER
​
{
  "id": "XXbSbGogfDbZAnnX",
  "type": "ping",
  "status": "finished",
  "createdAt": "2023-01-04T14:52:42.067Z",
  "updatedAt": "2023-01-04T14:52:52.768Z",
  "probesCount": 1,
  "results": [
    {
      "probe": {
        "continent": "EU",
        "region": "Western Europe",
        "country": "NL",
        "state": null,
        "city": "Naarden",
        "asn": 33915,
        "longitude": 5.1563,
        "latitude": 52.285,
        "network": "Vodafone Libertel B.V.",
        "tags": [],
        "resolvers": [
          "private"
        ]
      },
      "result": {
        "rawOutput": "PING gov.pl (194.181.92.98): 56 data bytes\nRequest timeout for icmp_seq 0\nRequest timeout for icmp_seq 1\n\n--- gov.pl ping statistics ---\n3 packets transmitted, 0 packets received, 100.0% packet loss",
        "resolvedAddress": "194.181.92.98",
        "resolvedHostname": null,
        "timings": [],
        "stats": {
          "min": null,
          "max": null,
          "avg": null,
          "loss": 100
        }
      }
    }
  ]
}
```

**Comment by jimaek** [comment]
Is this issue not applicable to other tests? Maybe we need a global parameter "status" or something like that?

@MartinKolarik what do you think?

**Comment by alexey-yarmosh** [comment]
`status: failed` makes sense for cases like making a ping to `asdf.asdf`:
```
{
  "id": "zILNhPUtRYQQYOrZ",
  "type": "ping",
  "status": "finished",
  "createdAt": "2023-01-04T15:44:02.169Z",
  "updatedAt": "2023-01-04T15:44:02.827Z",
  "probesCount": 1,
  "results": [
    {
      "probe": {
        "continent": "AS",
        "region": "Eastern Asia",
        "country": "KR",
        "state": null,
        "city": "Seoul",
        "asn": 40676,
        "longitude": 126.9777,
        "latitude": 37.5662,
        "network": "Psychz Networks",
        "tags": [],
        "resolvers": [
          "8.8.8.8",
          "8.8.4.4"
        ]
      },
      "result": {
        "rawOutput": "ping: asdf.asdf: Name or service not known",
        "resolvedAddress": null,
        "resolvedHostname": null,
        "timings": [],
        "stats": {
          "min": null,
          "max": null,
          "avg": null,
          "loss": null
        }
      }
    }
  ]
}
```

But than goes question how we will define that `100.0% packet loss` is 'successful' and `Name or service not known` is 'failed'. As both of them will be caught as execa errors.

**Comment by MartinKolarik** [comment]
100% loss is a successful result and what you propose above is correct @alexey-yarmosh  - `stats.loss` should be 100 and the resolved fields should have the correct values.

**Comment by MartinKolarik** [comment]
Please check how other tests behave in the same case, particularly MTR.

**Comment by alexey-yarmosh** [comment]
Seems we are also able to parse error rawOutput for traceroute and probably mtr
