### ISSUE TITLE
Use multiple cores by the API

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#224]
Currently we have a 4 cores CPU.
Node effectively uses only one of them.
We should consider options to load idle cores: cluster, worker_threads, etc.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/16905445/200317917-d267997c-a8a0-4cbb-84e8-c515986e68af.png">

**Comment by patrykcieszkowski** [comment]
I'm not seeing the core usage on this screenshot, but generally speaking there's no benefit to using worker_threads for I/O operations, and that's 90% (if not more) of what this API service is doing. I would say you should consider spawning new threads for CPU intensive work, like hashing, encryption or parsing and leave I/O operations with the main Event Loop.

**Comment by alexey-yarmosh** [comment]
`worker_threads` is only one of the ideas to consider. Key here is running 4 API instances on a 4 cores machine to increase the I/O throughput, and that most likely should be done either by node `cluster`, or on the high level - by docker swarm.

**Comment by jimaek** [comment]
> high level - by docker swarm.

Not possible, we use host networking, meaning only 1 container can run at any moment on a VM. Also it would probably increase pub-sub traffic and make syncing of probes more difficult. So ideally we want to only move specific operations to other threads and not run the whole API per thread.

**Comment by alexey-yarmosh** [comment]
we don't have intensive sync work to move from main thread. So when 2 VMs will not be enough we should choose between adding new VMs or running per thread.

**Comment by MartinKolarik** [comment]
`cluster` seems like the right thing to do, just needs to check how the messages are routed. We want them always delivered only to one client, not all clients.

**Comment by alexey-yarmosh** [comment]
The key thing here is to set up socket.io communication. Currently the only way to implement it is by using `@socket.io/redis-adapter` on every worker. While working correctly that means redis pub/sub traffic will increase dramatically:
currently - 1 fetchScokets with 2 instances with 1 worker generates 2 redis messages.
with 4 workers - 1 fetchSockets with 2 instances with 4 worker generates 8 redis messages.

As redis is our current bottleneck I am not sure we need to proceed with the solution described above. At least until https://github.com/jsdelivr/globalping/issues/269 is implemented.

I've posted a question about combining `@socket.io/redis-adapter` with `@socket.io/cluster-adapter`, more details can be found there: https://github.com/socketio/socket.io/discussions/4659

**Comment by alexey-yarmosh** [comment]
Linked issue:
https://github.com/socketio/socket.io-cluster-adapter/issues/1

**Comment by MartinKolarik** [comment]
The fetchSocket() calls are cached now, aren't they? The effect should not be that significant.

**Comment by alexey-yarmosh** [comment]
That is true, it is cached. And I don't think effect will be that big.

But anyway our servers are usually loaded on ~15% even under perf tests, while redis barely deals with the load. So we shouldn't make the narrow place more narrow to tune the API servers.

**Comment by alexey-yarmosh** [comment]
So what we can see on the image is that currently our bottleneck is the perf of the node process itself. (Redis CPU is ~3%, while API CPU is ~100%).
![image](https://user-images.githubusercontent.com/16905445/226561027-7aeca6bc-c21b-4299-a481-17ebad81c8ea.png)

From the flamegraph we are observing that that there are some sync operation done mostly by npm packages, those are:
- socket.io res/req encoding/decoding
- redis data JSON.stringifying before sending to the DB
- http validation
- a lot of small newrelic operations (not sure what they are)
![image](https://user-images.githubusercontent.com/16905445/226566236-d04a4366-92ef-4924-acdb-0b1b43f434f3.png)

We can't get rid of most of that operations, but we should benefit from doing them in parallel and applying a cluster to the API seems to make sense now.

Other possible optimizations:
- ipv4 check worth caching (it is the most heavy part of the http validation)
- redis operations are already pipelined (there is an internal queue, and it's size grows and shrinks while we are creating new `redis.json.set` promises). I'll additionally check that it is used in all cases.
- maybe we can benefit from redis lua scripts to move some `set` logic from node to redis.
- socket.io perf doesn't seem to be a problem (API's CPU is at 100% while there are ~4000 RPS through socket.io. Even old benchmarks showed that socket io is able to deal with [~10000RPS](https://drewww.github.io/socket.io-benchmarking/).
- there a lot of newrelic operations, as I remember API sends logs to NR itself, so probably that can be changed, but seems not more than that.

**Comment by MartinKolarik** [comment]
Can you explain the `500 * (1 + 2 + 4 * 2 + 1 + 1 + 2)` part? Does each probe make 15 writes per second per test (since this is multiplied by requests and time in the beginning)?

**Comment by alexey-yarmosh** [comment]
Not 15 writes per second, just 15 writes per probe per measurement. So it is 150000 writes overal, and since such measurement will take ~20 seconds to end it is 150000/20 = 7500 writes per second.

https://github.com/jsdelivr/globalping/issues/240#issuecomment-1359585466
