### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#228]
- Add /health endpoint with 200 status and text "Alive". "Alive" should only appear after the API has finished bootstrapping.
- Listen for SIGTERM triggers. It will be triggered by Docker doing redeployments
- When received change text to "Received SIGTERM, shutting down"
- Start timer of 15 seconds
- During this period disconnect any probe trying to connect.
- After 15 seconds gracefully exit the node.js app
- Make sure the API and probes can handle 2 separate API instances behind an LB. It should try to reconnect.

Question:
- Can we make the probes buffer test results locally if when sending output updates to the API the API goes down? The probe would then have to try to reconnect and when connection gets established it would send everything it has in the buffer.

This process will allow the load-balancer to monitor that endpoint and redirect all connections to the other API instance when its not "Alive".

**Comment by alexey-yarmosh** [comment]
> Can we make the probes buffer test results locally if when sending output updates to the API the API goes down? The probe would then have to try to reconnect and when connection gets established it would send everything it has in the buffer.

socket.io solves that problem https://socket.io/docs/v4/client-offline-behavior/
I've tested it behind the local haproxy:
- with 1 API instance - when killing API in the middle of the measurement, probes are waiting until it is up again to reconnect. After that they send all remaining measurement messages. No data loss.
- with 2 APIs behind the proxy - when killing API1 in the middle of the measurement probes of API1 reconnects to API2 and send all remaining measurement messages there. No data loss. The only problem is that after that all probes are connected to API2 even if API1 is up again.
