### ISSUE TITLE
Update tests to catch cjs compilation errors

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#231]
https://github.com/jsdelivr/globalping/pull/230

**Comment by alexey-yarmosh** [comment]
That is related to error prone ts compilation of .cjs files. More info here:
https://github.com/microsoft/TypeScript/issues/50647

Probably we can add a simple test to verify that compiled code is able to run.
Also, we should consider options to overcome the issues ourselves, so we are not stuck on ts v4.7.
