### ISSUE TITLE
System tags

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#236]
It was part of https://github.com/jsdelivr/globalping/issues/153 but now there is an urgent use case that requires this.

Specifically this part:

>System tags. On top of the above we would need to have our own tags that users cant change but can use to query probes. Example: public-dns, regional-dns, datacenter.

The goal at the moment is to tag specific probes that I control with custom tags per probe. I have servers with both AWS and Google Cloud and I need to tag each probe with the "cloud region name", e.g. "eu-west-1", "us-east-2"...

This way a user can then ask to ping from specific cloud regions, e.g. magic:google+eu-west-1

Not really sure how to do it since the system at the moment is ephemeral. It was supposed to be part of the dashboard epic but maybe we can build the system tags first somehow? I already have a mysql DB online for our Slack App. 

But if we do it now i dont want to have to migrate or rewrite anything as we continue on task #153 so it should be thought out. 

@MartinKolarik maybe you have ideas?

**Comment by jimaek** [comment]
A potential idea is to keep things ephemeral and add cloud specific code that would automatically detect if a probe is running on AWS or GCP and add extra metadata. e.g. https://stackoverflow.com/questions/4249488/find-region-from-within-an-ec2-instance

This way we dont need to use a DB at all until we're ready to start the epic.

**Comment by jimaek** [comment]
@MartinKolarik I think the above automated idea will be the best since it will allow us to re-use AWS/GCP probes hosted by other users. Can you confirm a final API format for tags to avoid any breaking future changes? It would combine ephemeral tags as described above, manual system tags set by admin stored in a DB and identified by IP, and user set tags also set in DB and identified by IP. 

After it goes live it will immediately be integrated by an important user and changing the formal will not be an option.

**Comment by jimaek** [comment]
@alexey-yarmosh We agreed on the above ephemeral tags format and logic as first step. Please read through and let me know what you think

**Comment by alexey-yarmosh** [comment]
It seems simpler and safer to determine region by API based on the ip of a probe. Maybe that will suit us?
https://stackoverflow.com/a/45441923
https://cloud.google.com/compute/docs/faq#find_ip_range

**Comment by jimaek** [comment]
So the API would download the IP lists same way it downloads blacklists on every start and then check the connecting IPs against them? I guess that sounds indeed simpler

**Comment by MartinKolarik** [comment]
I thought about reverse DNS lookups as well as the regions are in the hostnames too but I remember some thread on Twitter when @jimaek discussed this as an option for geo-locating the probes, and someone mentioned the IPs get reassigned across regions.

**Comment by jimaek** [comment]
If we use official IP list API endpoints I would assume they are correct and updated

https://ip-ranges.amazonaws.com/ip-ranges.json
https://www.gstatic.com/ipranges/cloud.json

**Comment by MartinKolarik** [comment]
I see, ok, that looks good.

**Comment by alexey-yarmosh** [comment]
> Then they can be queried by "tag:aws-eu-west-2" or "tag:u-username-whatever" or **"magic:aws-eu-west-2"**

If we are able to query tags using "magic:" nothing stops the user from creating a tag "belgium" and affect another user which was querying using magic but assuming country, e.g. { "magic": "belgium" }. Maybe tags should be queried only using "tags:smth"?

**Comment by MartinKolarik** [comment]
E.g. @alexey-yarmosh you personally would only be able to create tags that start with `u-alexey-yarmosh-` based on the last proposal.

**Comment by jimaek** [comment]
Tags are strict but magic is fuzzy, so u-alexey-yarmosh-belgium would match magic: Belgium.

So the solution seems to be excluding user tags from magic completely

**Comment by MartinKolarik** [comment]
Then I guess exclude user tags. But to be fair, the whole magic field is already quite broken as it is because of the fuzzy matching, if I'm reading it correctly. E.g. the example we have in the docs for `DE` as Germany is going to match mostly random places that have `DE` in the city or network name instead of the intended German locations: https://dl.dropboxusercontent.com/s/9f9xnr6jed0m8w1/2022-12-05_14-59-22.png

**Comment by jimaek** [comment]
Yeah we should probably make it smarter with priorities. I will open a separate issue about that

**Comment by jimaek** [comment]
Yes that's one of the use cases
