### ISSUE TITLE
Probes are distributed very unevenly between the API instances

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#237]
VMs should divide connected probes, which is not true now:

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/16905445/202520015-43a5d6f1-b563-411d-97dd-41217150b33c.png">

During deployment, VMs are launched one by one. When first VM starts all probes connect to it, then, when the second VM comes back online all probes are already connected to the first one and have no reason to reconnect.

Possible solution is to send a 'reconnect' message to every probe on the VM start. Flow:
1. We are forcing deploy
2. API1 is exiting
3. All probes connect to API2
4. API1` is deployed
5. API1` sends a reconnect message to probes through redis
6. Probes reconnect and are divided by APIs
7. API2 is exiting
8. All probes connect to API1`
9. API2` is deployed
10. API2` sends a reconnect message to probes through redis
11. Probes reconnect and are divided by APIs.

Since socket.io is able to buffer messages, there is no data loss.

**Comment by MartinKolarik** [comment]
Seems reasonable.

**Comment by patrykcieszkowski** [comment]
Won't probes be unavailable while they reconnect? It might be a good idea to randomise the delay between these reconnect requests, so they won't be all disconnected at once.
