### ISSUE TITLE
Review the transport used across API instances

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#244]
Under usual load [@socket.io/redis-adapter](https://github.com/socketio/socket.io-redis-adapter) works fine, however under the high load (>5 RPS * 100 probes) we are able to observe issues like #120 and #234. The root cause is that communication through redis pub/sub becomes very slow under the load. So to address issues above we need to deal with the adapter performance. 

Possible option:
1. tune redis itself
    1.1 run separate redis instances for storage and for API adapter (since their logic does not overlap, we are able to get fast perf boost)
    1.2 use dragonfly as an uderlying db for redis adapter (if the API is compatible it will be quickly to set up, and may give significant perf boost)
2. ~~use another adapter~~ (I tried AMQP and NATS adapter, but they are poorly supported and [don't have required functionality](https://github.com/jsdelivr/globalping/issues/120#issuecomment-1333467970))
3. use another way to communicate with probes (we can try something else instead of socket.io, with the built in horizontal-scaling. [link](https://blog.hotstar.com/building-pubsub-for-50m-concurrent-socket-connections-5506e3c3dabf))
    3.1 NATS
    3.2 MQTT
    3.3 uWebSockets?
    3.4 ...

**Comment by jimaek** [comment]
1. and 1.1: It doesnt seem to be possible to tune it other than clustering to utilize more cores. But that feels like a hack to me because the "high load" we have is not that high really, and if a normal installation cant handle it, adding clustering will only push the problem to the future and not really solve anything
1.2: The perf difference seems minimal I believe
3: Can you expand on that? You want to completely remove socket.io from the system? Or you want to use a queue system for a specific function?

Also uWebSockets is unrelated to "another way of communication", it won't solve any Redis problems.

**Comment by MartinKolarik** [comment]
Clustering to use more cores (if redis can't use all resources it has now) or use independent instances is the correct thing to do as far as redis scaling goes. I agree the current socket setup may not be ideal for our use case but no sure about the alternatives.

**Comment by jimaek** [comment]
I agree about clustering being correct, but I expected to do it in the future to scale to tens of thousands of probes and users, not because it struggles to handle 500 probes and a few requests. So if I scale it now we will only postpone the inevitable by a few months. Based on some online benchmarks Redis is simply super slow at this.

**Comment by patrykcieszkowski** [comment]
Just an idea: replace pub/sub with cache. Each instance periodically updates redis with their local probe list, instead of waiting for pub/sub request/response, just pull the data from redis whenever necessary.

**Comment by jimaek** [comment]
> Just an idea: replace pub/sub with cache. Each instance periodically updates redis with their local probe list, instead of waiting for pub/sub request/response, just pull the data from redis whenever necessary.

Wouldn't that mean if a probe goes down it will remain in the cache and API will try to send it measurements to execute?

**Comment by patrykcieszkowski** [comment]
Yes, and no. It will be shown on the list but the API can double check whether the requested probe is available at the time of executing a measurement. If it's already gone - ignore it (the measurement request is sent by the owner-instance). But if you run the update every 30sec, the likelihood of having these lists out of sync would be pretty low, but not impossible, while eliminating the pub/sub timeout.

It can possibly happen with the current implementation as well; every `GET /probes` request represents the current list of probes, but users are never guaranteed to receive results from the probe they've requested, as the probe might be gone by the time they send the measurement.

Another idea would be storing a local cache on every instance. and only updating it after it expires (30s intervals). That will eliminate the constant pub/sub load to n at the time (n = num of instances).

**Comment by MartinKolarik** [comment]
I already suggested doing that with a cache time of 200 ms on `fetchSockets()`, which should be enough to avoid too many calls yet be almost realtime. @alexey-yarmosh did you try that?

**Comment by alexey-yarmosh** [comment]
> I agree about clustering being correct, but I expected to do it in the future to scale to tens of thousands of probes and users, not because it struggles to handle 500 probes and a few requests

There are no any problems/bottlenecks from the service itself, all our reads/writes are valid.
What is the bottleneck is redis pub/sub that is used by socket.io-redis-adapter and its `fetchSockets` method. `fetchSockets` is used on every `POST /measurement` and `GET /probes` request. 

Under the hood `fetchSockets` works like that:
1. API1 publishes a message to redis pub/sub indicating the aim to fetch sockets from API2
2. API1 listens to the event with all sockets from API2 (for 250 probes it is about 175kb of data)
3. API1 merges the response with its local probes

During the tests fetchSockets() takes 300ms at the start and then 15000ms+ later.
We already moved from 1RPS*100probes to 5RPS*100probes just by moving redis close to the server.
So scale/cache/replace redis as a transport for APIs should be the next step.

**Comment by jimaek** [comment]
So would a 200ms cache help in this case? Can you benchmark it to see the results?

**Comment by alexey-yarmosh** [comment]
> I already suggested doing that with a cache time of 200 ms on fetchSockets(), which should be enough to avoid too many calls yet be almost realtime. @alexey-yarmosh did you try that?
didn't try yet, that might work

**Comment by alexey-yarmosh** [comment]
Here are the benchmark results with and without cache. 
Seems it gave us ~20% boost.

| Measurement                   | median T no cache | max T no cache | median T cache | max T cache |
|-------------------------------|-------------------|----------------|----------------|-------------|
| 100-probes-5-rps-240-duration | 74.4              | 831            | 58.6           | 1452        |
| 100-probes-6-rps-240-duration | 96.6              | 1211           | 82.3           | 704         |
| 100-probes-7-rps-240-duration | 9999.2            | 47727          | 608            | 15192       |
| 100-probes-8-rps-240-duration | 16819.2           | 58429          | 13770.3        | 50370       |


Code is located at https://github.com/jsdelivr/globalping/compare/fetch-sockets-cache#diff-33c943bb9434a4d28a0ca1f8c722aa293a591d0858ee54917e09c2d5f42af90b

**Comment by MartinKolarik** [comment]
We can also try a bit higher delay, e.g., 1 second.

**Comment by jimaek** [comment]
I would say 1s is maximum to avoid issues with disconnecting probes

**Comment by MartinKolarik** [comment]
Try it with 5 too to see what difference it makes.

**Comment by alexey-yarmosh** [comment]
Here are the results for other cache value.

| Measurement                   | median T no cache | max T no cache | median T 200ms cache | max T 200ms cache | median T 1000ms cache | max T 1000ms cache | median T 5000ms cache | max T 5000ms cache | 
|-------------------------------|-------------------|----------------|----------------|-------------|-------------|-------------|-------------|-------------|
| 100-probes-5-rps-240-duration | 74.4              | 831            | 58.6           | 1452        | 40.9        | 2162        | 37          | 1825        |
| 100-probes-6-rps-240-duration | 96.6              | 1211           | 82.3           | 704         | 40.9        | 991         | 37          | 719         |
| 100-probes-7-rps-240-duration | 9999.2            | 47727          | 608            | 15192       | 713.5       | 24944       | 1107.9      | 19563       |
| 100-probes-8-rps-240-duration | 16819.2           | 58429          | 13770.3        | 50370       | 12459.8     | 50420       | 9416.8      | 50407       |


I am concerned about possible error even for 200ms cache. If user's measurement consists of only 1 probe and we are directing his measurement to the disconnected probe because of a cache that will be empty response => error.

**Comment by alexey-yarmosh** [comment]
I will update the branch, add tests and create a PR
