### ISSUE TITLE
Smarter magic field

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#247]
The magic field should get a bit more logic to make the output more predictable. e.g. if you do magic:DE you will match not just Germany but every city and ISP that has "de" in their names and will get a random output.

At first I thought of a complicated system with weights, but after thinking about it I think there's a better one.

It sounds like the simplest solution would be to first sort the data in a way that makes most sense and then allow the system to select the first N matching values. e.g. a version of sorting could be:

1. ISO country names, DE
2. Country names, Germany
2. Cities, Berlin
3. US state, Texas
4. Continent, Europe
5. System tags
6. ISP names, Netia
7. ASN, 47875

This way if you do magic: DE limit:10 you should in theory just get 10 probes with ISO=DE and the check would never even get to "Belgrade" and "Clouvider" which also contain the text "DE". But if you do magic:DE with limit 1000 then its your problem that you will get random results and the solution is to use strict parameters and not magic.

BUT the data within each category should be random to avoid things where a single probe gets 100% of tests that ask for 1 measurement. 

I think the task itself should also include automated tests to avoid regression.

1. Write automated CI tests that ensure different combos of filters work correctly
8. Exclude user tags from magic
9. Add ranking system?

**Comment by patrykcieszkowski** [comment]
You could also add a support for optional type matching. `type=value`.

Then you don't have to sort or assume anything, and your results are more reliable.

**Comment by jimaek** [comment]
If the person knows what they're looking for they should just use the static parameters anyway. This is supposed to be a human friendly input where you can run something that you think should work and it works. Adding special formatting is probably not the best, it should just magically work :)

**Comment by alexey-yarmosh** [comment]
Looks valid, we can also combine that with the priority for full string match. To avoid bugs when city (or another lower priority field) fully sits inside the country name.

**Comment by alexey-yarmosh** [comment]
>As per value sorting, here's their current order:
>https://github.com/jsdelivr/globalping/blob/master/src/probe/builder.ts#L76-L89
>I think most of them are in their correct order already.

Does that affect the order? As I see we are only filtering by the values from index.
https://github.com/jsdelivr/globalping/blob/master/src/probe/router.ts#L60

**Comment by patrykcieszkowski** [comment]
> Does that affect the order? As I see we are only filtering by the values from index. https://github.com/jsdelivr/globalping/blob/master/src/probe/router.ts#L60
Yes, it will always pick the first result on the list. What you've linked is the matching mechanism for joined queries. E.g. `de + berlin`. But it also works on non-joined magic queries.

1. At line 59 we split the string by `+` sign, save it to a variable.
2. At line 60 we make sure the probe contains all tags extracted at line 59.

`every` returns true on all returned values being true.
`find` always looks up until it matches the first result.
`includes` matches for string combination within a string.

**Comment by patrykcieszkowski** [comment]
Correct. That captures the output of the `every` method. You can't sort the inputs, since the magic query is supposed to be guessing your intention. You have to sort the index list, which can only be sorted at the probe builder's level.

**Comment by MartinKolarik** [comment]
I'd say a better and more predictable logic is: if there's an exact match, ignore partial matches. They're likely to be wrong.

**Comment by MartinKolarik** [comment]
I said only if there's an exact match. How would it break in those cases?

**Comment by jimaek** [comment]
Ok in that case I can't think of a use-case breaking unless someone else can. 
But without implementing sorting the results would still suffer, wouldn't they?  e.g. magic:Grand Falls limit:1 would fuzzy match "Grand Falls-Windsor" city in Canada, but if "Grand Falls Europe Networks ISP" existed it could theoretically return that too. If we did sorting as above the city would rank higher and always return results from the city in Canada rather than the ISP in europe

**Comment by MartinKolarik** [comment]
@jimaek regarding your last comment:

> If we did sorting as above the city would rank higher and always return results from the city in Canada rather than the ISP in Europe

That's good. Matching both just adds confusion as they are not related at all. The first match should stop going to lower levels.

**Comment by MartinKolarik** [comment]
@alexey-yarmosh, please add the following stop rule: as we go from level 1 (city) through to level 8 (asn) in the list, if there's a match on level X, don't include any results from levels > X. In other words, if a country gets matched by ISO code, don't attempt to match full country names, cities, or anything else. Related issue: https://github.com/jsdelivr/globalping/issues/334
