### ISSUE TITLE
If measurement finishes by timeout its counter is not cleared

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#254]
Additionally no TTL is set so these records just eat space https://dl.dropboxusercontent.com/s/q3kvn3yhotj61m9/RedisInsight-v2_2022-12-10_19-02-11.png

**Comment by alexey-yarmosh** [comment]
Current behaviour (assuming measurement takes 40 seconds by the probe):
1. measurement is created 
2. timeout of 30 sec is created
3. `probes_awaiting` field is created with 30+5 sec TTL
4. waiting: 30 secs passes
5. timeout marks measurement as finished
6. waiting: 5 more secs passes
7. TTL deletes the `probes_awaiting` field
8. waiting: 5 more secs passing
9. measurement from probe returns and updates the finished measurement object with its data
10. measurement try to decr `probes_awaiting` field (already deleted by TTL) => new `probes_awaiting` field without TTL is created with -1 value

I'll handle point 10 either by ignoring or another TTL.
The question is should we update measurement data after marking it as finished? (currently we do)

**Comment by jimaek** [comment]
If the measurement has a hard limit of 30seconds then every action after 5 should not exist. 

The probe running the measurement needs to just kill the process after 30s and probably report back to API as timeout to get it marked as finished + additional status of "timeout".

**Comment by MartinKolarik** [comment]
The actions are correct, except the nine should probably ignore the data, and ten should have a check (implementation-wise, maybe it'll be easier to swap them, check for `probes_awaiting` first, and drop the data if it doesn't exist). Probes don't need to report anything on timeout because we can't rely on it, and there must be a timer on the API side anyway.

**Comment by alexey-yarmosh** [comment]
> The actions are correct, except the nine should probably ignore the data, and ten should have a check (implementation-wise, maybe it'll be easier to swap them, check for probes_awaiting first, and drop the data if it doesn't exist)

I was thinking about that too. Behavior will be exactly like we need. Plus we will get rid of a few redis operations.
