### ISSUE TITLE
[Probe] SSH Fingerprint changes on reboot

### ISSUE THREAD

**Issue by karkkijokeri** [jsdelivr/globalping#276]
Hello! I had this problem, where every time I restart the probe, the SSH fingerprint changes, so I have to manually remove the old line from `known_hosts` to be able to connect.

**Comment by jimaek** [comment]
Hey, it's not a bug but the result of our security measures. The probe basically resets on every reboot and doesn't retain information including ssh keys.

I think it should be fine since there's no real reason to use the ssh connection other than verifying it works after the first boot.

**Comment by karkkijokeri** [comment]
> Hey, it's not a bug but the result of our security measures. The probe basically resets on every reboot and doesn't retain information including ssh keys.
> 
> I think it should be fine since there's no real reason to use the ssh connection other than verifying it works after the first boot.

Is it possible to make openssh ignore the fingerprint change?
(I want to spy if people use my probe)

**Comment by jimaek** [comment]
Sure plenty of ways. Both using the command and config https://askubuntu.com/questions/87449/how-to-disable-strict-host-key-checking-in-ssh 

Check it out, I believe most solutions should work

**Comment by karkkijokeri** [comment]
Thanks! Also a question; do I need an static ip, and can people dos my internet via this?

**Comment by jimaek** [comment]
Static IP is not needed, all connections are only outgoing. And no they can't dos you, we have rate limits and antibuse logic to prevent targeting and overloading a specific probe.

**Comment by karkkijokeri** [comment]
Great
