### ISSUE TITLE
Add new fields to the results of dns and http measurements

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#284]
New fields for the results of dns and http measurements should be added:

1. to http command:
`statusCodeName: string` (e.g. `statusCodeName: 'OK'`) - is taken from https://github.com/sindresorhus/got/blob/main/documentation/3-streams.md#statusmessage

2. to dns command:
`statusCodeName: string` (e.g. `statusCodeName: 'NOERROR'`) - is taken from the rawOutput:
```
; <<>> DiG 9.16.27-Debian <<>> google.com -t A -p 53 -4 +timeout=3 +tries=2 +nocookie
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20734
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;google.com.\t\t\tIN\tA

;; ANSWER SECTION:
google.com.\t\t197\tIN\tA\t142.251.129.78

;; Query time: 0 msec
;; SERVER: x.x.x.x#53(x.x.x.x)
;; WHEN: Wed Feb 01 13:44:54 UTC 2023
;; MSG SIZE  rcvd: 55
```
3. to dns command:
`statusCode: number` (e.g. `statusCode: 0`) - is mapped based on `statusCodeName` value + our static map (actual values can be found here https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#table-dns-parameters-6)

**Comment by jimaek** [comment]
@ayuhito Please review in case it impacts CLI or Slack app

**Comment by ayuhito** [comment]
Should be fine with no issues!

**Comment by alexey-yarmosh** [comment]
Completed in https://github.com/jsdelivr/globalping/issues/270
