### ISSUE TITLE
Fix default "ready": true status of the probes

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#294]
Currently all our probes are considered [READY] by default. And only after determining the location we are checking dependencies (existence of unbuffer command) and explicitly send either ‘probe:status:ready’ or ‘probe:status:not_ready’ from the probe.

So there is a small window, not more than a few secs, when we don’t know if unbuffer is available for the probe. But still can send a measurement to it.

source from API - https://github.com/jsdelivr/globalping/blob/master/src/probe/builder.ts#L98
source from probe - https://github.com/jsdelivr/globalping-probe/blob/master/src/helper/api-connect-handler.ts#L15

This behavior should be updated either to set ready to "false" by default or to completely remove ready/not-ready logic as it seems to be obsolet. (Linked issue https://github.com/jsdelivr/globalping-probe/issues/71)

**Comment by jimaek** [comment]
Not sure if removing makes sense, wouldn't that mean that the probe would be able to receive tests when we dont know it's Geo? (now it can, but we should fix it)

**Comment by patrykcieszkowski** [comment]
The current mechanism tells you if the probe is ready to accept connections, not whether the backend is ready to handle the probe.

**Comment by alexey-yarmosh** [comment]
Ok, it makes sense to mark probe as "not ready" before determining its geo. That can be done easily.
 
But I am not sure check for unbuffer should happen in probe's "location" event handler. 
BTW for what reason for unbuffer to be absent? If it's only `http://ftp.nl.debian.org` is unavailable maybe it makes sense to just store DEB files in sources or as a part of a docker image.

**Comment by jimaek** [comment]
Its already part of the docker image. But it wasnt part of the original one, so we needed a way to add unbuffer without having to re-pull the new docker image (most probes will never have their docker container updated).
So we needed a way to install unbuffer in case the probe is still running the old docker container that never had unbuffer installed

**Comment by alexey-yarmosh** [comment]
And is it still an issue? Since there are no [NOT READY] probes currently on api.globalping.io

**Comment by jimaek** [comment]
No idea. We wont know until we remove that hack and see how many NOT READY appear.

**Comment by alexey-yarmosh** [comment]
Let's just update the default to [NOT READY] then.

**Comment by jimaek** [comment]
So by default all probes connect as NOT READY until all checks are done and they get marked as READY?
Sounds logical to me as someone as any objections? @patrykcieszkowski ?

**Comment by patrykcieszkowski** [comment]
Alex is correct, in that the API sets the probe status as `ready` by default. Immediately after that, it emits the `api:connect:location` event, and the probe responds with `ready/not-ready` event in response.

So the probe may appear as `ready` initially after it has reconnected for a second of few.

> And is it still an issue? Since there are no [NOT READY] probes currently on api.globalping.io

It might not be an issue, but it still makes sense to keep this logic in place, in case there was an urgent need to push some breaking changes. Setting it to `not-ready` by default is probably better though.
