### ISSUE TITLE
Use Lua scripts for redis key counting

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#312]
Right now, in `updateMeasurementCount()`, we iterate over all measurements using a default scan size, which is ten records. That means about 7k calls just to count the keys. We could use a larger batch size as in store `cleanup()` but since we don't need the keys at all, just their count, it's still a lot of unnecessary IO. We should replace this with a small lua script, similar to [this](https://stackoverflow.com/questions/52167955/use-lua-script-with-scan-command-to-obtain-the-list) that just returns the number of matching keys. The redis client has built-in support for script handling: https://github.com/redis/node-redis#lua-scripts

**Comment by alexey-yarmosh** [comment]
As I see we may also benefit from using lua scripts in places with a chain of calls where next call is based on the data of the previous one:
- https://github.com/jsdelivr/globalping/blob/master/src/measurement/runner.ts#L53-L62

And in places with multiple parallel redis operations:
- https://github.com/jsdelivr/globalping/blob/master/src/measurement/store.ts#L36-L49
