### ISSUE TITLE
lower QA requirements

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#315]
I think we should lower the requirements from 10 packets to 8 or even 6. Too many probes seem to fail all the time and when testing manually 5-8 packets seem to be stable but once I ask 10 packets I often get packet loss.

**Comment by MartinKolarik** [comment]
That's somewhat suspicious. The ping should have 0 loss with a virtually unlimited number of packets on a stable connection. If something in the user's network can't handle a single 10 packets ping, there's a good chance the same thing will affect test results.

**Comment by jimaek** [comment]
I've seen this behavior from what I consider stable probes like Google Cloud and DO, so not sure. Unfortunately I cant verify every single one because I dont have access. Check the logs of your probe too, do you get a lot of failed qa tests?

**Comment by MartinKolarik** [comment]
No errors on mine though I only see logs for the past few hours.

**Comment by jimaek** [comment]
Give it some time. Here is an example https://gist.github.com/jimaek/fe4df059f5dd41de5c7650f62d1b1585

**Comment by MartinKolarik** [comment]
Ok let's lower it to 6.
