### ISSUE TITLE
Optimize GET operations

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#318]
Depending on the measurement type and the number of probes, the resulting response may end up fairly big. In the most extreme cases, it's around 10 MB uncompressed. At such sizes, the JSON operations that usually have negligible performance impact start to matter:
 - JSON.parse() when reading from redis - about 25 ms,
 - JSON.stringify() when sending the data to the client - about 70 ms.

This sums up to about 100 ms of purely CPU time per request, while most of it is spent doing useless work because we don't actually need the parsed values on the server that much. If we read the data as a single string from redis and sent it directly to the client without the parse/stringify cycle, it would result in considerable performance benefits (based on my tests, about 50-60% overall reduction in response time).

The necessary changes would be:
 - store `createdAt` / `updatedAt` in the ISO format internally instead of timestamps that are converted on-demand,
 - change the internal format of the `results` object to be simply an array where each probe is identified by its index instead of a random id (to match the public output format),
 - remove the `last-modified` header from the response (it isn't so important because we have etags).

Then, the raw value can be read like this: `this.redis.sendCommand([ 'JSON.GET', getMeasurementKey(id) ])`

Note that because the JSON won't be prettified in this case, the etag computation and compression get about 50 % faster too, because the resulting string is much shorter.

**Comment by jimaek** [comment]
>change the format of the results object to be simply an array where each probe is identified by its index instead of a random,

Is that a breaking change for API users?

**Comment by MartinKolarik** [comment]
It's a change of the internal storage format to match the output format 1:1 and avoid additional transformations. Not visible to the users, except for the measurements that were stored before the change - those would break unless we migrate them.

**Comment by alexey-yarmosh** [comment]
Since results will be stored as an array, how we will save the result of a specific test? Currently id is used as a part of path:
```js
await this.redis.json.set(key, `$.results.${data.testId}.result.rawOutput`, data.result.rawOutput);
// or
await this.redis.json.set(key, `$.results.${data.testId}.result`, data.result);
```
We need something like JS's `Array.prototype.find()` but seems there is no analogue in redis.

**Comment by MartinKolarik** [comment]
`$.results[${index}].result`

**Comment by alexey-yarmosh** [comment]
But how we will know the `index` without additional get operation?
The only way I see is to pass the index to the probe. In that case we can also completely get rid of `testId` property.

**Comment by MartinKolarik** [comment]
That's exactly what I meant, make the `testId` the index in the array. I believe we only use it internally and it only needs to be unique within the measurement, so there's no reason to have random ids instead of just numbers.
