### ISSUE TITLE
Limits endpoint

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#328]
We need an endpoint that the user and all tools could call to see the limits that apply to the user.

E.g. anon would see something like "max:100, used:50, available:50, type:IP"

Later we would expand it to understand API keys and show remaining credits. But the format would be different so need a way to combine them.

**Comment by MartinKolarik** [comment]
I'm thinking this format, where:
 - `type` is `ip` or `user`,
 - `read` is returned only if it applies (doesn't right now, might to anon users after #526),
 - `credits` section is returned if the request is authenticated

```json
{
  "rateLimit": {
    "measurements": {
      "create": {
        "type": "ip",
        "limit": 500,
        "consumed": 150,
        "remaining": 350,
        "reset": 1240
      },
      "read": {
        "type": "ip",
        "limit": 25000,
        "consumed": 150,
        "remaining": 350,
        "reset": 1240
      }
    }
  },
  "credits": {
    "remaining": 1240
  }
}
```
