### ISSUE TITLE
Setting limit to higher than available probes return data from other regions

### ISSUE THREAD

**Issue by perosb** [jsdelivr/globalping#334]
Setting the limit to f.ex 3 and only want to test from Vietnam that only have 2 probes, returns result from a third arbitrary probe.
Maybe this should either:
1. throw error
2. return result from one of the existing probes in VN again (might be troublesome if limit 1000 hammering probe)

I'm thinking this might give incorrect analysis unless you're observant.

As a comparison, selecting a country with 0 probes shows an error.

```
~ $ globalping ping jsdelivr.com from VN --limit 3
> AS, VN, Muong Lay, ASN:45899, VNPT Corp
PING jsdelivr.com (104.21.35.47) 56(84) bytes of data.
64 bytes from 104.21.35.47 (104.21.35.47): icmp_seq=1 ttl=55 time=29.0 ms

> AS, VN, Hanoi, ASN:135905, VIETNAM POSTS AND TELECOMMUNICATIONS GROUP
PING jsdelivr.com (104.21.35.47) 56(84) bytes of data.
64 bytes from 104.21.35.47 (104.21.35.47): icmp_seq=1 ttl=58 time=19.1 ms

> EU, HU, Budapest, ASN:30836, 23VNet Kft.
PING jsdelivr.com (104.21.35.47) 56(84) bytes of data.
64 bytes from 104.21.35.47 (104.21.35.47): icmp_seq=1 ttl=58 time=20.7 ms
```

edit: just noticed that setting `from #ASN` with high limit only return the correct ASN

**Comment by jimaek** [comment]
Its not arbitrary, it returns the last one because "23VNet" contains "VN" and it matches it

**Comment by jimaek** [comment]
I think you could just use Vietnam as input and it would fix the issue :)

**Comment by perosb** [comment]
Ah, that explains this scenario but might be more confusing.

None the less, this was just a suggestion for improvements.

**Comment by MartinKolarik** [comment]
This is confusing and Vietnam might break as well in the future, which is why I said partial matches should be ignored if there's an exact match. E.g., if the input is an ISO code, nothing else than ISO codes should be considered:  https://github.com/jsdelivr/globalping/issues/247#issuecomment-1339815722 We need to revisit that.

**Comment by patrykcieszkowski** [comment]
> but I cant imagine how a user would use them

```globalping ping jsdelivr.com from country=VN --limit 3```

**Comment by jimaek** [comment]
> > but I cant imagine how a user would use them
> 
> `globalping ping jsdelivr.com from country=VN --limit 3`

I mean why :) Passing VN to magic will work after the fix and even if it didn't Vietnam would work too. So not sure we need to support strict location parameters

**Comment by jimaek** [comment]
Seems correct now:

```
# globalping ping jsdelivr.com from VN --limit 3
> AS, VN, Hanoi, ASN:135905, VIETNAM POSTS AND TELECOMMUNICATIONS GROUP
PING jsdelivr.com (172.67.213.229) 56(84) bytes of data.
64 bytes from 172.67.213.229 (172.67.213.229): icmp_seq=1 ttl=58 time=67.4 ms
64 bytes from 172.67.213.229 (172.67.213.229): icmp_seq=2 ttl=58 time=67.5 ms
64 bytes from 172.67.213.229 (172.67.213.229): icmp_seq=3 ttl=58 time=67.6 ms

--- jsdelivr.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 401ms
rtt min/avg/max/mdev = 67.397/67.491/67.604/0.085 ms

> AS, VN, Viet Tri, ASN:45899, VNPT Corp
PING jsdelivr.com (172.67.213.229) 56(84) bytes of data.
64 bytes from 172.67.213.229 (172.67.213.229): icmp_seq=1 ttl=57 time=67.2 ms
64 bytes from 172.67.213.229 (172.67.213.229): icmp_seq=2 ttl=57 time=68.0 ms
64 bytes from 172.67.213.229 (172.67.213.229): icmp_seq=3 ttl=57 time=67.5 ms

--- jsdelivr.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 403ms
rtt min/avg/max/mdev = 67.171/67.572/68.049/0.362 ms
```
