### ISSUE TITLE
Lua in places with multiple parallel redis operations:

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#344]
And in places with multiple parallel redis operations:
- https://github.com/jsdelivr/globalping/blob/master/src/measurement/store.ts#L36-L49

_Originally posted by @alexey-yarmosh in https://github.com/jsdelivr/globalping/issues/312#issuecomment-1514418796_

**Comment by MartinKolarik** [comment]
@alexey-yarmosh was faster #343
