### ISSUE TITLE
HTTP2 rawHeaders should not contain pseudo headers

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#355]
https://stackoverflow.com/questions/63009619/http-2-specific-headers

Right now we include it in `rawHeaders` but somehow not in `rawOutput`:
![image](https://github.com/jsdelivr/globalping/assets/6192491/c0c56096-f77f-424e-b2b4-db49b597a921)

Also worth looking into: can we get the missing timing fields for HTTP2 or is that just https://github.com/jsdelivr/globalping-probe/issues/131 ?

**Comment by alexey-yarmosh** [comment]
<img width="737" alt="image" src="https://github.com/jsdelivr/globalping/assets/16905445/adca117d-920c-4da5-b9b1-87e45fc4ce4b">

pseudo headers should still be there inside `headers` object, right?

**Comment by alexey-yarmosh** [comment]
got doesn't provide timings info for `dns`, `tls` and `tcp` in case of HTTP2. That is the reason they are `null` in the result. Seems Patryk have faced that previously https://github.com/sindresorhus/got/issues/2056
