### ISSUE TITLE
Support north instead of just northern

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#361]
I think we should support this format as well:
- West europe (instead of western)
- north america (instead of northern)
and so on

**Comment by MartinKolarik** [comment]
1. North/South America do make sense but as aliases to continents, not regions (we do the same with countries): https://github.com/jsdelivr/globalping/blob/dd8720dfeafddfe8831d1d1cc9f27160ca1912af/src/probe/builder.ts#L67-L70 Adding the full names as aliases could be done for all continents.

2. West/east/north/south Europe and anything else, *do not* make sense, and are not used:
![image](https://github.com/jsdelivr/globalping/assets/6192491/ffd2f6a8-329d-4623-bd37-63bf424eda1b)

3. In the rare cases where the other variant is used, it refers to something else than the region. E.g. "South Africa" is a single country (and we support that correctly), "Southern Africa" is a region with five counties (and we support that correctly as well).

**Comment by jimaek** [comment]
Its not about what is used on the internet, its about what a user might think to enter, and entering a wrong but shorter version of what he wants is absolutely possible and I have tried to do it myself. Basically adding an alias to every "western->west" version will improve UX

**Comment by MartinKolarik** [comment]
Regardless of our disagreement on whether this is useful, it can't be done for *every* case for the reason I explained above (3). If you really want the other variants as region aliases (and only for magic), they will have to be checked individually to avoid conflicts.

Continent names should still be handled separately, as explained in (1).

**Comment by jimaek** [comment]
Continents is the obvious and should be done. But like I said its about convenience. Can we just add aliases to regions that make sense and don't break anything?

**Comment by MartinKolarik** [comment]
@alexey-yarmosh please do the continents as described above and then also region aliases for the cases where the other variant doesn't conflict with anything else. The regional aliases should be fully internal, not shown to the user, and apply only to magic.

**Comment by alexey-yarmosh** [comment]
So in case of `{"magic": "South Africa"}` we will filter by country, and in case of `{"magic": "North Africa"}` by region. Correct?

**Comment by jimaek** [comment]
Sounds correct
