### ISSUE TITLE
Update IP limits logic

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#364]
Right now:
 - limits reset each minute
 - one measurement costs 1 credit

Correct behavior:
 - limits reset every hour
 - measurement costs 1 credit for each selected probe

Note that if I set `limit: 100` but there are only 20 probes matching the location, the cost is 20. That means we need to either:
a) allocate the credits only after the probes are selected,
b) or allocate credits based on the limit but add them back if there are not enough probes.

To not disrupt the existing use cases before we have the tokens, the limit should be set to at least 100k for now (which is, e.g. 200 measurements x 500 locations), but later it'll be around 300.

Note that once we implement support for tokes (in a separate step), there'll be a separate (higher) per-token limit with the same cost/reset logic.

**Comment by jimaek** [comment]
Partially discussed here too https://github.com/jsdelivr/globalping/issues/53
