### ISSUE TITLE
Some probes are being selected too often

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#366]
PM me for logs.

It seems that when running tests with location "world" some specific probes are being selected way too often for no reason. I think there is a bug in the selection logic, almost if it just alphabetically sorts all probes and selects the top few.

Need to check why it happens with world, if it happens with other regions too and how to make it smarter.

**Comment by alexey-yarmosh** [comment]
Monitoring charts show the increased number of request during the period of the logs provided. So all of the probes experienced ~the same load like the probe from the issues. That is also confirmed by logs from a few other probes.

Also I ran 130 measurements with that body: 
```
{
    "target": "google.com",
    "type": "ping",
    "limit": 15,
    "locations": [{
        "magic": "world"
    }]
}
```
Which requires ~2000 probes in total. And 600+ different probes was used during that, so randomisation work as expected.
