### ISSUE TITLE
IP limit log abuse

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#367]
Our logs are filled with the same probes trying and failing to connect due to sharing the same IP. 
They all reconnect every second and have generated 2million records.

We should force them to pause and maybe try to connect once per minute or something like that. And use user-friendly errors same as described here https://github.com/jsdelivr/globalping-probe/issues/152

**Comment by alexey-yarmosh** [comment]
I will reduce the amount of logs generated + the logic will be: in case of ip limit wait 1 min before next attempt, if error is still there 1 min delay will repeat again and again until successful connection.
