### ISSUE TITLE
Update throttling of fetchSockets function

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#368]
Current behaviour:
1. first `throttledFetchSockets` request comes
2. it triggers `io.fetchSockets`, resolves and provides the response
3. second `throttledFetchSockets` request comes 
4. it need to wait for `fetchSocketsCacheTTL` then do its request and provide the response

On step 4 instead of waiting for `fetchSocketsCacheTTL` time it can respond with the value from first throttledFetchSockets request.

We can also go further and store sockets list in memory and respond with it immediately to every request, while updating the list every `fetchSocketsCacheTTL` time.

**Comment by MartinKolarik** [comment]
> it need to wait for fetchSocketsCacheTTL then do its request and provide the response

It should be like this: any call that comes before `fetchSocketsCacheTTL` gets the previous result right away. Any call that comes after `fetchSocketsCacheTTL` triggers a new execution immediately, and waits for its result (this ensures we don't use too old data). If the package we use does something else, we should indeed change it.

**Comment by alexey-yarmosh** [comment]
>  any call that comes before fetchSocketsCacheTTL gets the previous result right away

that is the main point, instead of getting the result right away, all such calls wait for the `fetchSocketsCacheTTL` time to end, then wait for the real request result and only then resolve.

**Comment by jimaek** [comment]
Is this related to the constant `timeout reached while waiting for fetchSockets response` we're getting at the moment?

**Comment by alexey-yarmosh** [comment]
It is related, but not a 100% fix for that.
Btw, it will fix https://github.com/jsdelivr/globalping/issues/385
