### ISSUE TITLE
Suburbs to city names

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#379]
Related to https://github.com/jsdelivr/globalping/issues/264#issuecomment-1592913583

>A lot of mismatches happen because of preferring the suburb city instead of the main city (e.g. Dadri and Delhi) That is a point to think, do we want probes to be as accurate as possible (so user will be able to filter by Dadri, but filter by Delhi will not return that probe) or we want to accumulate all suburb cities in main city. Third option is to combine both and show that probe both in Dadri and Delhi searches. Other examples: Doddaballapura and Bangalore, Piscataway and New York.

>Top thing to do is to find the main city for district/suburb. We can try geonames.org API or similar tools for that. For example [here](https://www.geonames.org/8133088/spanga.html) under the Hierarchy tab we can see that Spanga refers to Stockholm.

**Comment by jimaek** [comment]
Note: Ideally we should make probes quarriable by both suburb and main city. So a probe could be in London and Red Bridge at the same time

**Comment by MartinKolarik** [comment]
Most recent details https://github.com/jsdelivr/globalping/issues/264#issuecomment-1629455226
