### ISSUE TITLE
Allow private IPs for DNS tests

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#384]
Let's allow the API to return tests with private IPs only in this case:
- DNS test
- Valid public hostname is used. 

E.g. 
broken.example.com -> 192.168.1.1 is ok
dev.home -> 192.168.1.1 is blocked like all other tests

**Comment by MartinKolarik** [comment]
Many networking devices register themselves under public hostnames, e.g., Asus routers use `router.asus.com`, TP-Link uses `tplinkwifi.net`

**Comment by jimaek** [comment]
I don't think it should be a problem knowing the IP of the router, it's visible as hop during traceroute anyway

**Comment by MartinKolarik** [comment]
Hmm, it is, ok... and what's the use case here?

**Comment by jimaek** [comment]
Misconfigured routing, e.g. DNS based CDN

**Comment by MartinKolarik** [comment]
Ok.
