### ISSUE TITLE
probes endpoint is too slow

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#385]
We use https://api.globalping.io/v1/probes quite heavily on our website and currently the response time is 2-6 seconds.
Need to optimize that. Can we cache the responses in RAM or set cache headers to cache in the browser?

**Comment by MartinKolarik** [comment]
Let's start by #368 and then I'll recheck.

**Comment by alexey-yarmosh** [comment]
https://github.com/jsdelivr/globalping/issues/368 is fixed and /probes endpoint feels much better now.
