### ISSUE TITLE
Reduce the amount of data sent to newrelic

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#391]
We are generating too much data from the API to newrelic. Need to check if that is possible to reduce that amount to stay under our current plan.

**Comment by alexey-yarmosh** [comment]
The amount of data is growing and hit the limit again, need to optimise it further.

**Comment by jimaek** [comment]
Looks like we duplicate some logs, a small example https://share.perfstack.net/2023/12/chrome_2023-12-03_14-06-20.png
