### ISSUE TITLE
Error: ip limit during probes reconnect

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#404]
Usage of cached fetchSockets response in probe-ip-limit.ts leads to Error: ip limit.

Scenario:

- probe1 is connected to the api
- some operation (e.g. /probes ednpoint) calls fetchSockets
- fetchSockets result (including probe1) is return and cached for 1 sec
- during that 1 sec probe1 is reconnecting (e.g. because of ping timeout)
- probe-ip-limit.ts calls fetchSockets and gets cached result (with probe1 in a list)
- that lead to Error: ip limit

**Comment by jimaek** [comment]
After deploy the issue seems to be still present. Logs provided
