### ISSUE TITLE
Reduce the amount of data sent through redis during fetchSockets

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#419]
On the image there is data generated by a single connected probe during fetchSockets request. Most of it either rarely changes (probe info), or not required by the app logic (socket metadata).

Instead it will be nice to transfer only identificators of probes (ip and socketId for example) and all other data may be cached in memory and updated through a dedicated redis collection.

That may require to write an analogue of `@socket.io/redis-adapter` ourselves, but since fetchSockets is used almost in all app operations that may significantly improve perf.

<img width="1337" alt="image" src="https://github.com/jsdelivr/globalping/assets/16905445/1cdf6924-564b-4e5a-a080-b7f65c5eeb03">

**Comment by MartinKolarik** [comment]
I've been thinking about customizing the sync mechanism, too, but it seems like a considerable amount of work that may not be necessary in the end. I'd keep this as an "idea" but probably not something to do right away.

**Comment by alexey-yarmosh** [comment]
I think `fetchSockets` on a creation of a measurement should be replaced anyway, as it doesn't scales. Possible alternatives are:
- A shared list of sockets in redis. It is regularly updated by the API instances (e.g. every 5 sec) with the probes connected to that instance. On a create measurement request instance only reads that list from redis, filters, and passes the measurement to the required probes through `@socket.io/redis-adapter` or redis pub/sub.
- A sync of instances through redis pub/sub. Every instance regularly publishes a list of probes connected to it, other instances subscribes, reads and updates their local list of all probes. Then, during create measurement request, a list of all probes is available instantly without additional requests.

In both options separating of probe ip (sync only ips) and probe metadata (storing it separately in redis and memory)  makes sense.
