### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by mfld-pub** [jsdelivr/globalping#422]
I see references to IPv6 in the code but in the CLI I cannot start any tasks where the target is an IPv6 address. Is there a hidden flag or something ?

**Comment by jimaek** [comment]
Hey, at the moment we're focusing on new features and decided to postpone ipv6 support for later when we'll be able to spend the time and resources needed to ensure complete support of ipv6 in every system.

**Comment by mfld-pub** [comment]
Cool, I will hold off on deploying further probes and monitor release notes. We are IPv6-only :(

I love the CLI and the ease of creating queries. Solid project! 

Just needs v6 🙏

**Comment by kescherCode** [comment]
Indeed, we just received a node but cannot deploy it behind an IPv6-only network. That is a shame, and I hope the "possibly later" becomes a "implemented" soon!

**Comment by kescherCode** [comment]
(Indeed, nodes should also be able to communicate which IP versions they can communicate with to begin with.)

**Comment by jimaek** [comment]
We will begin work on ipv6 after we launch our dashboard and the required functionality for it to be useful to all users, e.g. API keys, probe management. Probably late Q1.

I invite you to keep your probes connected and they will automatically start working once the functionality goes live :)

**Comment by MartinKolarik** [comment]
I opened a fresh issue to track all the IPv6-related requirements. Please subscribe there if you want to be notified of updates: https://github.com/jsdelivr/globalping/issues/447
