### ISSUE TITLE
Support sorting probes by latency

### ISSUE THREAD

**Issue by alissonlauffer** [jsdelivr/globalping#424]
Sometimes I want to identify the probes with the best/worst latency to a specific host (to detect issues). It would be helpful to have the ability to sort probes based on their latency.

Thanks for this project, I'm currently hosting three probes.

**Comment by jimaek** [comment]
Thanks for the feedback, I also want to add something like that. I think it will be done as part of this task https://github.com/jsdelivr/www.jsdelivr.com/issues/578
