### ISSUE TITLE
Use socket.io rooms to categorize the probes

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#429]
We can put  all probes in the rooms by their ip. Then it will be possible to `await io.in(ip).fetchSockets()` in the ip-limit.ts to fetch only the socket with the same ip, instead of fetching the full list and filtering it by ip then.

Also we can use rooms to categorize probes by country, city, ISP, etc. So if measurement request has e.g. specific country we are able to do `fetchSockets` only in the specific room and reduce the amount of data transfered.

**Comment by MartinKolarik** [comment]
Closing this as no longer applicable / solved in a different way.
