### ISSUE TITLE
Can I use the globalping source code to build my own service?

### ISSUE THREAD

**Issue by input01** [jsdelivr/globalping#432]
hello, the project is perfect, and I want to build my own globalping API server and globalping probe with the source code.
But I was not found the License like MIT, apache2, and so on.
Can I do that?

**Comment by jimaek** [comment]
Hey, we will formally update the license very soon to make things clearer. So, yes you can do it, but we won't be able to offer any support as we're trying to focus all of our resources towards the service and codebase as a package.
