### ISSUE TITLE
New sys tags, eyeball networks

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#434]
Lets tag all probes with new system tags:
- eyeball-network
- dc-network

I think we can use the "hosting" parameter of ipinfo. If true then dc-network, if false then eyeball.

I think when using the magic field we could then set a location to "amsterdam+eyeball" to limit the probes to non-datacenter, right?

Also as part of this task need to update the site, readme, api docs to make sure people know about this tag.

**Comment by alexey-yarmosh** [comment]
>I think when using the magic field we could then set a location to "amsterdam+eyeball" to limit the probes to non-datacenter, right?

yes

**Comment by MartinKolarik** [comment]
The options we have here:
 - ipinfo `privacy.hosting` (as suggested) https://ipinfo.io/developers/privacy-detection-database
 - maxmind `traits.isHostingProvider`
 - ip2location `usage_type` (https://blog.ip2location.com/knowledge-base/what-is-usage-type/)

So the question is if we just use ipinfo regardless of who wins the city location or something more advanced. The very first IP I tried, ipinfo got it wrong, so maybe it's worth testing each on our verified IP list.

**Comment by jimaek** [comment]
Based on what I've read I trust ipinfo more, so maybe we can keep things simple? I was only thinking if we need a fallback or not. 

Also I think the maxmind parameter you quoted is on the more expensive tier than the one we pay.

**Comment by MartinKolarik** [comment]
I don't mind keeping it simple, but I'm somewhat skeptical now that it got an OVH IP wrong. The parameters I listed are what we get in our responses so we have access to all three.

**Comment by jimaek** [comment]
We have access but we pay per query, and that parameter is part of the more expensive query type. At least that's what I see in the UI.
I dont really worry about accuracy here, we should allow people to modify this field for their own probes too. 
I only worry about an ipinfo outage, but I guess the cached data should be enough to keep us running for a while

**Comment by jimaek** [comment]
The current state is unfortunately unusable. Out of 950 probes we tagged only 13 as eyeball and about 5 of those are definitely wrong. 


Are you sure we're using ipinfo correctly?

**Comment by jimaek** [comment]
After purging the cache and getting more tags we have lots of false positives. I think we should be using a different ipinfo field.
e.g. https://ipinfo.io/45.150.242.131
it has hosting=false in the privacy section, but ASN type=hosting.

Can we switch the check from hosting to asn type?

**Comment by MartinKolarik** [comment]
That doesn't seem any better, even my home IP address has ASN `type:
"hosting"`

**Comment by jimaek** [comment]
Maybe you're an outlier? A bunch of IPs I tested were correct when using the ASN type field

**Comment by MartinKolarik** [comment]
I'll do some comparisons and report back...

**Comment by MartinKolarik** [comment]
Actually, we would have to make a second request to https://ipinfo.io/products/asn-api to get that field. It isn't available in the Geolocation results. Also, the IP you previously posted as an example has "type=business" now.

**Comment by jimaek** [comment]
both type business and hosting are correct for non-eyeball probes. So the ASN field still seems better
