### ISSUE TITLE
HTTP 422 with error type `no_probes_found` when using `region` location filter to create measurement

### ISSUE THREAD

**Issue by zry98** [jsdelivr/globalping#444]
However, `magic` filter works for region names.

Example request:
```json
{
  "type": "ping",
  "target": "google.com",
  "locations": [
    {
      "region": "Northern America",
      "limit": 1
    }
  ]
}
```

Response:
```json
{
  "error": {
    "type": "no_probes_found",
    "message": "No suitable probes found."
  },
  "links": {
    "documentation": "https://www.jsdelivr.com/docs/api.globalping.io#post-/v1/measurements"
  }
}
```

**Comment by zry98** [comment]
Has the official API at `https://api.globalping.io/v1/` got the fix yet? I'm still experiencing this issue. Thanks!

**Comment by MartinKolarik** [comment]
Not yet, we'll deploy the fixed version likely next day - I'll let you know.

**Comment by zry98** [comment]
> Not yet, we'll deploy the fixed version likely next day - I'll let you know.

Thanks!

**Comment by MartinKolarik** [comment]
Fixed now! Thanks for reporting.
