### ISSUE TITLE
Adopted probes should generate credits

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#452]
Similar to how recurrent sponsorships add credits over time, adopted probes should generate credits for their owners. To be decided:
 - how often we add  add the credit (24 hours?),
 - how much, although this should be configurable.

**Comment by jimaek** [comment]
Once per day makes sense, with some logic where it has to stay up at least 20 hours during that day to be counted.

**Comment by alexey-yarmosh** [comment]
I am thinking about having a cron to call `/probes` every 10 mins with 5 min deviation. If probe was found in the response increment new `onlineTimes` field by 1. If at the end of a day `onlineTimes > 20 * 6`, assign credits. Then set `onlineTimes` to 0. Time intervals are configurable.

**Comment by MartinKolarik** [comment]
Seems reasonable.

**Comment by jimaek** [comment]
Btw we will need to add anti abuse logic at some point, but I'm guessing it won't impact the current implemention and we can come back to it later?

**Comment by alexey-yarmosh** [comment]
What abuse scenario do you mean?

**Comment by jimaek** [comment]
Credits farming, e.g. starting 500 probes with some super cheap hosting provider. 

I would add rules like limiting the number of probes from the same ASN, same ASN+same city.

Maybe also a global probe limit per account

**Comment by alexey-yarmosh** [comment]
@jimaek should we assign credits for probes in any status or only in "ready"?

**Comment by jimaek** [comment]
Only ready, the probe should be active and process measurements to get credits
