### ISSUE TITLE
Split redis use to persistent and non-persistent part

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#456]
We store many different types of information in redis, and for some, the schema often changes between deployments, which causes errors that can't be easily caught by tests and requires manually deleting the old data (recently, this applies to geoip data cache several times).

A pattern I used to solve this on other projects:
 - use two redis databases, threat one as persistent (like now), and the other as non-persistent,
 - call `flushdb()` on the non-persistent one on node process startup,
 - make the non-persistent version default (`getRedisClient()`) and the persistent version opt-in (`getPersistentRedisClient`).

In our case, persistent should be the measurement data, and rate-limiting, not sure if anything else.

**Comment by alexey-yarmosh** [comment]
By 2 redis dbs you mean 2 selectable redis databases on one instance, not two separate instances, right?

**Comment by MartinKolarik** [comment]
yes
