### ISSUE TITLE
Default uppercase `World` does not work on website

### ISSUE THREAD

**Issue by MarvinJWendt** [jsdelivr/globalping#462]
Hi, by default, the `Location` field on the website is set to `World`. This results in only a single selected probe. If I manually set it to `world`, it works as expected:

## Default (uppercase `World`)
![image](https://github.com/jsdelivr/globalping/assets/31022056/67cadba0-f637-4b83-bb7b-37a1790b2020)

## Manually changed to `world`
![image](https://github.com/jsdelivr/globalping/assets/31022056/11af6aac-10a1-4846-a968-5df98ed1c0b3)

**Comment by jimaek** [comment]
Thanks for reporting, it will be deployed during the weekend
