### ISSUE TITLE
Default "World" location always picks WorldStream B.V. (AS49981)

### ISSUE THREAD

**Issue by heyajulia** [jsdelivr/globalping#465]
"World" with an uppercase W always picks AS49981+Rotterdam because the ASN name (WorldStream B.V.) starts with "World."

![image](https://github.com/jsdelivr/globalping/assets/68656233/ab1e1c16-7112-4790-a38e-647967b1a0c9)

"world" with a lowercase W works as expected, and picks a random location:

![image](https://github.com/jsdelivr/globalping/assets/68656233/f411d3ae-2c79-49a5-9906-c72a8f01c7de)

I can also replicate this using the globalping CLI (`globalping ping cdn.jsdelivr.net from World` vs. `globalping ping cdn.jsdelivr.net from world`).

I'm not sure if this is related, but I'm physically located in The Netherlands.

**Comment by jimaek** [comment]
Hey, thank you for reporting. We have already fixed this issue as reported here https://github.com/jsdelivr/globalping/issues/462 and the fix will go live this weekend :)

**Comment by heyajulia** [comment]
Oops, sorry. I did not see that issue. 😅 Thanks for your hard work!
