### ISSUE TITLE
Open more DNS record types

### ISSUE THREAD

**Issue by cherinyy** [jsdelivr/globalping#466]
I noticed that Globalping limits the types of DNS records it can query, which is inconvenient.

![image](https://github.com/jsdelivr/globalping/assets/9050713/1eca4992-0c68-4cd0-b8e6-8d3e012db36a)

It would be nice if Globalping could be like Google Public DNS with your own input and selection.

![image](https://github.com/jsdelivr/globalping/assets/9050713/882b9d7c-1af3-4f47-8d7b-508c4fe54d59)

**Comment by jimaek** [comment]
May I ask which specific DNS types are the most important for you and example use cases? For now we're trying to implement the most important functionality and make sure its production ready.

**Comment by cherinyy** [comment]
> May I ask which specific DNS types are the most important for you and example use cases?

For my personal use, I only need to add one type, `HTTPS`.

This involves the use of HTTP/3 and ECH.

**Comment by cherinyy** [comment]
> Ok, then I think we can close this issue and keep this instead #467 But FYI you can already use HTTPS based resolvers using our HTTP test rather than DNS.

Maybe you may have misunderstood what I meant? I'm talking about Type 65 `HTTPS` records, not DoH.

```
# dig www.jsdelivr.com HTTPS

; <<>> DiG 9.18.11 <<>> www.jsdelivr.com HTTPS
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20140
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.jsdelivr.com.              IN      HTTPS

;; ANSWER SECTION:
www.jsdelivr.com.       300     IN      HTTPS   1 . alpn="h3,h2" ipv4hint=104.21.23.24,172.67.208.113 ipv6hint=2606:4700:3035::6815:1718,2606:4700:3037::ac43:d071

;; Query time: 190 msec
;; SERVER: ::1#53(::1) (UDP)
;; WHEN: Tue Jan 09 01:23:56 CST 2024
;; MSG SIZE  rcvd: 118
```

**Comment by jimaek** [comment]
Indeed, I opened a separate issue for that. This way it will be easier to implement and track.
