### ISSUE TITLE
anti-abuse IPv6

### ISSUE THREAD

**Issue by valeria-frckova** [jsdelivr/globalping#492]
As a part of #447. I'm currently trying to find a list of malicious IPv6 addresses to compare against. Most of the reputable sources are paid. This is what I've found so far:
[spamhouse](https://www.spamhaus.org/drop/dropv6.txt)
[team-cymru](https://www.team-cymru.org/Services/Bogons/fullbogons-ipv6.txt)

do you have any suggestions?

also, domains listed in domain blocklists are both IPv4 and IPv6 already?

**Comment by jimaek** [comment]
There are a few more here https://www.blacklistmaster.com/blacklists
I think in the past I had the best luck by checking the source code of related projects on GitHub. Like firewall rules generators that take in lists of bad IPs

**Comment by MartinKolarik** [comment]
@jimaek 

> also, domains listed in domain blocklists are both IPv4 and IPv6 already?

This should be the case, right? No need for new domain lists.

**Comment by jimaek** [comment]
It's not applicable as we don't try to resolve the domains before blocking. So yes, stays as is
