### ISSUE TITLE
Add extra TLS data

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#500]
Currently we only publish this data:

```
        "tls": {
          "authorized": true,
          "createdAt": "2024-02-05T08:03:56.000Z",
          "expiresAt": "2024-04-29T08:03:55.000Z",
          "issuer": {
            "C": "US",
            "O": "Google Trust Services LLC",
            "CN": "GTS CA 1C3"
          },
          "subject": {
            "CN": "*.google.com",
            "alt": "DNS:*.google.com, ..."
          }
```

Lets expand it and add the following:
all fingerprints, public key, key type (e.g. rsa2048,sha512,ecc256...)

**Comment by alexey-yarmosh** [comment]
Not sure how to define key type, we have key itself as a Uint8Array and nothing else related. Some sources mention checks like `pubkey.length === 65 && pubkey[0] === 0x04` but looks not very reliable. @MartinKolarik maybe you have any ideas?

![image](https://github.com/jsdelivr/globalping/assets/16905445/f468b0e5-81ad-4fda-8672-05a5475bf147)
