### ISSUE TITLE
Exponential backoff for probes

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#52]
Exponential backoff associated with failing tests. Need to make sure that probes with poor results are not ruining the tests. The goal is to prevent dial-up users from breaking the service.
Probably need to also log probes in "backing-off" state to make sure we dont lose half our network due to a bug in this system.

**Comment by jimaek** [comment]
It should also understand probes behind firewalls and either blacklist them or only blacklist specific measurement types per probe. 

Related https://github.com/jsdelivr/globalping/issues/243

**Comment by jimaek** [comment]
- 3 ping tests to test ICMP
- 3 HTTP HEAD tests to test TCP/HTTP
- 3 different endpoints like Cloudflare, Akamai, Fastly (make sure it works in China)
- Tests every minute. Before test NOT-READY. After test set new field https://github.com/jsdelivr/globalping/issues/296

**Comment by alexey-yarmosh** [comment]
Types of faulty probes:
- **ICMP is blocked**
can be covered by initial QA test

- **TCP is blocked**
can be covered by initial QA test

- **network is unstable => measurement timeouts**
can be covered by initial QA test + periodic QA tests

- **network is unstable => constant reconnects**
can't be covered by QA tests, so if we need to address that - separate mechanism of counting the disconnects is required
