### ISSUE TITLE
Limit of measurements

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#53]
Right now we have a simple anti-abuse system that simply rate-limits the amount of POST requests we accept per IP. Thats fine but its only an anti-abuse system.

We also need an extensive system to allow us to limit the amount of actual tests a user can run. e.g. I want to set 200 tests limit per hour per IP address with no authentication.
In theory that IP can now run either 1 measurement with limit of probes set to 200, and if we actual have 200 probes we run the test and return the results. But all future measurement requests will be declined until the 1 hour limit resets.

Or it can run 200 POST requests asking for 1 probe in each, same thing from the limit's point of view.

Need to make sure here that we correctly count them. So if a user has a limit of 200 and asks for 200 probes in Poland but we only have 50 probes in Poland that means that after the tests finish he will still have 150 tests remaining for that hour.

Later we will expand this for custom limits per API key and plan it's subscribed to, but at the moment its not necessary. 

Needs #153

**Comment by jimaek** [comment]
measurement = a single POST requesting a number of tests to be made by setting the limit parameter
test = the command the probes process. A measurement with limit of 10 would result in 10 tests

My proposed limits are below. There is no real reasoning behind them, just what feels right, small enough to avoid abuse, but large enough to be useful and not run out in the middle of testing. Feel free to comment.

**Global for everyone**:
- 100 POST requests per minute per IP
- Unlimited GET
- Max total 500 probes per measurement
- Remove limit per location (current 200?)

**No auth - Per IP**:
- 100 tests per hour

**Free user - API key present - No IP limits**
- 250 tests per hour

**Paid user  - API key present - No IP limits**
- $5 for 2000 credits? Where 1 credit = 1 test

So instead of creating plans I suggest we simply add credits based on the $ sponsored.
That should work both for one-time donations and subscribers. 

So if you just need to run a few tests for a single problem you donate one-time $5 to get more credits. But if you're writing a script or app that will use Globalping continuously then you would subscribe to a monthly GitHub Sponsors plan.

If a user has 1000 credits and starts running tests, he will first eat up the free 250 tests and then instead of get rate-limited he will go above the limit by using the credits until they run out. 

This would require a complete credits system that can:
- Understand hourly limits that reset and dont add up
- Pick up GitHub Sponsors changes. One-time/subscription/cancelled...
- Adopted probes generate credits every day that can be used
- Admin can add/remove credits per user

**Comment by MartinKolarik** [comment]
@jimaek since the auth and related features will be live soon, can we agree on the final limits here to use and document? I think the numbers above are fairly reasonable, maybe for credits, we could go with a simple $1 = 1k credits. Right now, we actually have $1 = 10k credits, which seems too high.

**Comment by MartinKolarik** [comment]
Closing as this is partly implemented, and the rest is covered by other open issues + the table.
