### ISSUE TITLE
Creating a measurement using Globalping API with HttpOptions is not successful

### ISSUE THREAD

**Issue by piquark6046** [jsdelivr/globalping#535]
[Screencast from 2024-08-01 10-52-49.webm](https://github.com/user-attachments/assets/acc1fad8-66b9-4dd4-bad9-25c9f50b832e)

I think that there is a bug on your backend side because I checked with https://www.jsdelivr.com/docs/api.globalping.io#post-/v1/measurements to find my error but not found.

**Comment by MartinKolarik** [comment]
Hey, `HttpOptions` is just the name of the type, the request format is:

```
measurementOptions: {
  request: { ... }
}
```

**Comment by alexey-yarmosh** [comment]
For "Bad Request" errors API responds with the details of the problem, which is useful in your and similar cases:
```json
{
  "error": {
    "type": "validation_error",
    "message": "Parameter validation failed.",
    "params": {
      "measurementOptions.HttpOptions": "\"measurementOptions.HttpOptions\" is not allowed"
    }
  },
  "links": {
    "documentation": "https://www.jsdelivr.com/docs/api.globalping.io#post-/v1/measurements"
  }
}
```

**Comment by piquark6046** [comment]
OK. Thanks.
