### ISSUE TITLE
Check random e2e failures

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#536]
https://github.com/jsdelivr/globalping/actions/runs/10320878547/job/28572446539#step:6:1074
https://github.com/jsdelivr/globalping/actions/runs/10321158227/job/28573377490#step:6:436

Reproducible (in a few attempts) locally. Suspecting https://github.com/jsdelivr/globalping/blob/6934953f8667740712e208802148c4928205aac6/src/lib/ws/helper/reconnect-probes.ts#L13 based on the logs.

**Comment by alexey-yarmosh** [comment]
Main reason indeed was probe reconnection logic, it is now disabled in e2e.
Also, 1 time I got probe stuck on `Checking for the latest version`, may be it was just a connection problem, but if repeated should be addressed too:
https://github.com/jsdelivr/globalping/actions/runs/10816945087/job/30009228800#step:6:335
