### ISSUE TITLE
Not generating credits with physical probe

### ISSUE THREAD

**Issue by bartgrefte** [jsdelivr/globalping#563]
On the dashboard it says "+150 / day" credits, well, since I fired up the physical probe last Sunday I have received none.

There's a Dutch forum with a [topic](https://gathering.tweakers.net/forum/list_messages/2261684) about the Globalping probe, there are more people there who are not receiving credits.

Since there hasn't been an IP-address change, nor has there been downtime, and there are more people running into this, I'm wondering what the cause might be.

Probe v1, version:0.33.2

edit: After having read the most recent messages in that topic, seems a bug was found and has been resolved.

**Comment by jimaek** [comment]
As your edit says we found and fixed a related issue. Please check if everything is working properly

**Comment by bartgrefte** [comment]
@jimaek Check, seeing credits :)

**Comment by jimaek** [comment]
Awesome, feel free to ping us if you encounter any other issues or have feedback
