### ISSUE TITLE
Dashboard probe sync issues

### ISSUE THREAD

**Issue by mfld-pub** [jsdelivr/globalping#572]
![image](https://github.com/user-attachments/assets/6da5fddd-3b97-447d-aa73-b96aec759914)

Checking probe logs I can see them actively doing work. 

I can also 

```ping globalping ping 8.8.8.8 -F <my tag> -L 26```

 and I see every one of them returning. 

I am certain I do not have 26 probes on 4 continents offline right now. 

Something is glitching.

**Comment by MartinKolarik** [comment]
They should be online now but I'll keep this open until we fix the underlying cause.

**Comment by mfld-pub** [comment]
22 on 4 off now. I will check if those 4 are really offline.
