### ISSUE TITLE
[Feature Request] Show probe versions in the probe table

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/globalping#573]
<img width="1533" alt="Google Chrome 2024-11-19 10 26 55" src="https://github.com/user-attachments/assets/6750a039-93a7-412e-9e6c-770197db1f4f">

So the table here doesn't provide any probe version information. But it is shown in the overview:

<img width="1257" alt="image" src="https://github.com/user-attachments/assets/f5e4a910-dbcb-4761-b4cb-dcdf2981b8e7">

**Comment by MartinKolarik** [comment]
See  jsdelivr/globalping-dash#45
