### ISSUE TITLE
New APM and logging service

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#577]
With New Relic getting pushy, and frankly its not very good either, we should start looking into alternatives. 

Some requirements:

- Low cost and predictable pricing
- Proper tracing with DB and Redis integration
- Server stats
- Logging without worrying
- Custom stats
- Simple to deploy and simple to use with good UX

**Comment by jimaek** [comment]
Stuff to track for custom dashboards (all timeseries):

- Number of total measurements and per type
- Total number of measurements between users and anons(unique IP)
- Target hostnames to track abuse
- Registered users
- Total probes and adopted probes
- Probes per continent
- Stored measurements vs expired

**Comment by MartinKolarik** [comment]
Closing as mostly done, ping me in DM for any minor adjustments. I don't really see a way to track "expired" measurements at the moment.

**Comment by jimaek** [comment]
Doesn't Redis have that? Expired vs active keys

**Comment by MartinKolarik** [comment]
Yes, but it's a single number as a total for the server. *Maybe* if we added our own tracking to capture the daily difference it would be somewhat useful.

**Comment by jimaek** [comment]
Oh and lets build charts per reported client. So we would have charts for CLI, Slack, Web tools and separately all the other third-party (per UA)
