### ISSUE TITLE
http command

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#91]
We need a new http type of measurement. Probably use https://github.com/sindresorhus/got. It supports everything except HTTP3 but its coming soon. The URL must be manually built from the parameters.

**http**
- method {HEAD} - The type of request to make. GET or HEAD. Default is HEAD (optional)
- path {/path/somewhere.jpg} - the path part that we will add to "target" to build the URL. Must support query strings, hashbangs and everything else.  Default none (optional)
- protocol {https} - the protocol to use and to be added to the URL. Technically if user selects HTTPS we just make it part of the URL. But if he selects HTTP2 or 3 then we use HTTPS in the URL and set extra parameters to support http/2 and http/3. Supported HTTP,HTTPS,HTTP2,HTTP3. Default HTTPS. (optional)
- port {543} - Port to connect to, default is 443 if HTTPS/http2/http3 and 80 if HTTP. (Optional.)
- host {string.com} - the value for the `host: ` header. Default is $target (optional)
- headers {array} -  key:value array that allows the user to set custom headers except from "host" which is above. Default non (optional)

Set internal parameters on our side:
- user-agent should be `globalping probe (https://github.com/jsdelivr/globalping)`
- 10 second total timeout `request: 10000`
- disable all caches
- followRedirect: false
- set dns resolver if present in global option
- dnsLookupIpVersion:4
- http2 is set based on user but note this: "If you prefer to use the newest version, set both request to http2wrapper.auto and http2 to true."
- rejectUnauthorized:false to accept expired certs
- Don't actually download anything to disk. It should all be in memory and sent to the API.
- Limit download size of content to 10kb!!! If the content being fetched is longer then we need to stop it immediately and send back to the API the first 10kb. This should be enough to fetch simple content like JSON endpoints or raw HTML pages.
- Make sure its multi-threaded same as the rest https://github.com/jsdelivr/globalping-probe/issues/10

Output:
- raw output. If HEAD then the raw headers. If GET then body without headers.
- parsed output of headers in all cases
- performance meta-data: dns lookup, tcp connection, tls handshake, time to first byte, download, total time
- tls certificate meta-data like issuer, domain, issue and expiration date, valid bool...

Must support the same global parameters, especially the resolver. But make sure we still check the hostname or IP part of the URL against our blacklist.

Global parameters:
- target - hostname or IP address (required) 
- resolver {1.1.1.1} - empty means local resolve (optional)
- limit {5} - empty means 1 per selected location (optional)
- continent -  (optional)
- country -  (optional)
- region -  (optional)
- state -  (optional)
- city -  (optional)
- asn -  (optional)"

**Comment by patrykcieszkowski** [comment]
> * host {string.com} - the value for the `host: ` header. Default is $target (optional)

how can this value be optional?

**Comment by jimaek** [comment]
All HTTP2 tests seem to fail with `Response code 400 (Bad Request)` Can you please test, maybe I am doing something wrong?

**Comment by jimaek** [comment]
>Limit download size of content to 10kb!!! If the content being fetched is longer then we need to stop it immediately and send back to the API the first 10kb. This should be enough to fetch simple content like JSON endpoints or raw HTML pages.

This part doesnt seem to work as described. It just returns "Exceeded the download." instead of first 10kb

**Comment by jimaek** [comment]
Where

```
        "tls": {
          "authorized": true,

```
is coming from? Because it reports authorized: true to HTTP requests too. Where its not even applicable. So not sure if that field works correctly

**Comment by patrykcieszkowski** [comment]
> All HTTP2 tests seem to fail with `Response code 400 (Bad Request)` Can you please test, maybe I am doing something wrong?

Not all servers support HTTP2. Here's my list:
- google.com - doesnt work
- youtube.com - doesnt work
- github.com - works
- odysee.com - works
- elocast.com - works
- stackoverflow.com - works
- gab.com - works
- linkedin.com - works

**Comment by patrykcieszkowski** [comment]
> Where
> 
> ```
>         "tls": {
>           "authorized": true,
> ```
> 
> is coming from? Because it reports authorized: true to HTTP requests too. Where its not even applicable. So not sure if that field works correctly

On what url did you get this response? Its only added, if we detect TLS response, and its a 1:1 mapping with `socket.authorized` variable.

**Comment by patrykcieszkowski** [comment]
> > Limit download size of content to 10kb!!! If the content being fetched is longer then we need to stop it immediately and send back to the API the first 10kb. This should be enough to fetch simple content like JSON endpoints or raw HTML pages.
> 
> This part doesnt seem to work as described. It just returns "Exceeded the download." instead of first 10kb

Error hander kicked in. I'll add an exception.
