### ISSUE TITLE
Probe IDs

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#94]
How about we expose each probe's unique ID and make the test quarable by the ID?
Example use-case:
I want to run a test from Amazon probe located in Canada. There is no way to set 2 filters at the moment, like country:canada + asn:amazon to run a test only on that specific probe.
But if we had IDs then the user could use /probes to filter as much as he wants and then simply use the IDs he needs

**Comment by jimaek** [comment]
We implemented the filters part. @MartinKolarik any thoughts on unique IDs and using them to target probes?

**Comment by MartinKolarik** [comment]
At this point, I see no reason to allow it. We could consider it later if there's a good use case.

**Comment by jimaek** [comment]
Then I'll close it and see if anyone opens a new issue about it
